#ifndef ATL_RESTRICT
#if defined(__STDC_VERSION__) && (__STDC_VERSION__/100 >= 1999)
   #define ATL_RESTRICT restrict
#else
   #define ATL_RESTRICT
#endif
#endif
#ifndef ATL_RESTRICT
#if defined(__STDC_VERSION__) && (__STDC_VERSION__/100 >= 1999)
   #define ATL_RESTRICT restrict
#else
   #define ATL_RESTRICT
#endif
#endif
#ifndef ATL_RESTRICT
#if defined(__STDC_VERSION__) && (__STDC_VERSION__/100 >= 1999)
   #define ATL_RESTRICT restrict
#else
   #define ATL_RESTRICT
#endif
#endif
static void ATL_cJIK0x0x66TN1x1x66_a1_bX
   (const int M, const int N, const int K, const float alpha, const float * ATL_RESTRICT A, const int lda, const float * ATL_RESTRICT B, const int ldb, const float beta, float * ATL_RESTRICT C, const int ldc)
/*
 * matmul with TA=T, TB=N, MB=0, NB=0, KB=66, 
 * lda=66, ldb=66, ldc=0, mu=1, nu=1, ku=66, pf=0
 * Generated by ATLAS/tune/blas/gemm/emit_mm.c (3.9.23)
 */
{
   #define Mb M
   #define Nb N
   const float *stM = A + (((Mb) << 6)+((Mb) << 1));
   const float *stN = B + (((Nb) << 6)+((Nb) << 1));
   #define incAk 66
   const int incAm = 0, incAn = -(((Mb) << 6)+((Mb) << 1));
   #define incBk 66
   const int incBm = -66, incBn = 66;
   #define incCm 2
   const int incCn = (((ldc) << 1)) - (((Mb) << 1));
   float *pC0=C;
   const float *pA0=A;
   const float *pB0=B;
   register int k;
   register float rA0;
   register float rB0;
   register float rC0_0;
   do /* N-loop */
   {
      do /* M-loop */
      {
         rA0 = beta;
         rC0_0 = *pC0;
         rC0_0 *= rA0;
         rA0 = *pA0;
         rB0 = *pB0;
         rC0_0 += rA0 * rB0;
         rA0 = pA0[1];
         rB0 = pB0[1];
         rC0_0 += rA0 * rB0;
         rA0 = pA0[2];
         rB0 = pB0[2];
         rC0_0 += rA0 * rB0;
         rA0 = pA0[3];
         rB0 = pB0[3];
         rC0_0 += rA0 * rB0;
         rA0 = pA0[4];
         rB0 = pB0[4];
         rC0_0 += rA0 * rB0;
         rA0 = pA0[5];
         rB0 = pB0[5];
         rC0_0 += rA0 * rB0;
         rA0 = pA0[6];
         rB0 = pB0[6];
         rC0_0 += rA0 * rB0;
         rA0 = pA0[7];
         rB0 = pB0[7];
         rC0_0 += rA0 * rB0;
         rA0 = pA0[8];
         rB0 = pB0[8];
         rC0_0 += rA0 * rB0;
         rA0 = pA0[9];
         rB0 = pB0[9];
         rC0_0 += rA0 * rB0;
         rA0 = pA0[10];
         rB0 = pB0[10];
         rC0_0 += rA0 * rB0;
         rA0 = pA0[11];
         rB0 = pB0[11];
         rC0_0 += rA0 * rB0;
         rA0 = pA0[12];
         rB0 = pB0[12];
         rC0_0 += rA0 * rB0;
         rA0 = pA0[13];
         rB0 = pB0[13];
         rC0_0 += rA0 * rB0;
         rA0 = pA0[14];
         rB0 = pB0[14];
         rC0_0 += rA0 * rB0;
         rA0 = pA0[15];
         rB0 = pB0[15];
         rC0_0 += rA0 * rB0;
         rA0 = pA0[16];
         rB0 = pB0[16];
         rC0_0 += rA0 * rB0;
         rA0 = pA0[17];
         rB0 = pB0[17];
         rC0_0 += rA0 * rB0;
         rA0 = pA0[18];
         rB0 = pB0[18];
         rC0_0 += rA0 * rB0;
         rA0 = pA0[19];
         rB0 = pB0[19];
         rC0_0 += rA0 * rB0;
         rA0 = pA0[20];
         rB0 = pB0[20];
         rC0_0 += rA0 * rB0;
         rA0 = pA0[21];
         rB0 = pB0[21];
         rC0_0 += rA0 * rB0;
         rA0 = pA0[22];
         rB0 = pB0[22];
         rC0_0 += rA0 * rB0;
         rA0 = pA0[23];
         rB0 = pB0[23];
         rC0_0 += rA0 * rB0;
         rA0 = pA0[24];
         rB0 = pB0[24];
         rC0_0 += rA0 * rB0;
         rA0 = pA0[25];
         rB0 = pB0[25];
         rC0_0 += rA0 * rB0;
         rA0 = pA0[26];
         rB0 = pB0[26];
         rC0_0 += rA0 * rB0;
         rA0 = pA0[27];
         rB0 = pB0[27];
         rC0_0 += rA0 * rB0;
         rA0 = pA0[28];
         rB0 = pB0[28];
         rC0_0 += rA0 * rB0;
         rA0 = pA0[29];
         rB0 = pB0[29];
         rC0_0 += rA0 * rB0;
         rA0 = pA0[30];
         rB0 = pB0[30];
         rC0_0 += rA0 * rB0;
         rA0 = pA0[31];
         rB0 = pB0[31];
         rC0_0 += rA0 * rB0;
         rA0 = pA0[32];
         rB0 = pB0[32];
         rC0_0 += rA0 * rB0;
         rA0 = pA0[33];
         rB0 = pB0[33];
         rC0_0 += rA0 * rB0;
         rA0 = pA0[34];
         rB0 = pB0[34];
         rC0_0 += rA0 * rB0;
         rA0 = pA0[35];
         rB0 = pB0[35];
         rC0_0 += rA0 * rB0;
         rA0 = pA0[36];
         rB0 = pB0[36];
         rC0_0 += rA0 * rB0;
         rA0 = pA0[37];
         rB0 = pB0[37];
         rC0_0 += rA0 * rB0;
         rA0 = pA0[38];
         rB0 = pB0[38];
         rC0_0 += rA0 * rB0;
         rA0 = pA0[39];
         rB0 = pB0[39];
         rC0_0 += rA0 * rB0;
         rA0 = pA0[40];
         rB0 = pB0[40];
         rC0_0 += rA0 * rB0;
         rA0 = pA0[41];
         rB0 = pB0[41];
         rC0_0 += rA0 * rB0;
         rA0 = pA0[42];
         rB0 = pB0[42];
         rC0_0 += rA0 * rB0;
         rA0 = pA0[43];
         rB0 = pB0[43];
         rC0_0 += rA0 * rB0;
         rA0 = pA0[44];
         rB0 = pB0[44];
         rC0_0 += rA0 * rB0;
         rA0 = pA0[45];
         rB0 = pB0[45];
         rC0_0 += rA0 * rB0;
         rA0 = pA0[46];
         rB0 = pB0[46];
         rC0_0 += rA0 * rB0;
         rA0 = pA0[47];
         rB0 = pB0[47];
         rC0_0 += rA0 * rB0;
         rA0 = pA0[48];
         rB0 = pB0[48];
         rC0_0 += rA0 * rB0;
         rA0 = pA0[49];
         rB0 = pB0[49];
         rC0_0 += rA0 * rB0;
         rA0 = pA0[50];
         rB0 = pB0[50];
         rC0_0 += rA0 * rB0;
         rA0 = pA0[51];
         rB0 = pB0[51];
         rC0_0 += rA0 * rB0;
         rA0 = pA0[52];
         rB0 = pB0[52];
         rC0_0 += rA0 * rB0;
         rA0 = pA0[53];
         rB0 = pB0[53];
         rC0_0 += rA0 * rB0;
         rA0 = pA0[54];
         rB0 = pB0[54];
         rC0_0 += rA0 * rB0;
         rA0 = pA0[55];
         rB0 = pB0[55];
         rC0_0 += rA0 * rB0;
         rA0 = pA0[56];
         rB0 = pB0[56];
         rC0_0 += rA0 * rB0;
         rA0 = pA0[57];
         rB0 = pB0[57];
         rC0_0 += rA0 * rB0;
         rA0 = pA0[58];
         rB0 = pB0[58];
         rC0_0 += rA0 * rB0;
         rA0 = pA0[59];
         rB0 = pB0[59];
         rC0_0 += rA0 * rB0;
         rA0 = pA0[60];
         rB0 = pB0[60];
         rC0_0 += rA0 * rB0;
         rA0 = pA0[61];
         rB0 = pB0[61];
         rC0_0 += rA0 * rB0;
         rA0 = pA0[62];
         rB0 = pB0[62];
         rC0_0 += rA0 * rB0;
         rA0 = pA0[63];
         rB0 = pB0[63];
         rC0_0 += rA0 * rB0;
         rA0 = pA0[64];
         rB0 = pB0[64];
         rC0_0 += rA0 * rB0;
         rA0 = pA0[65];
         rB0 = pB0[65];
         rC0_0 += rA0 * rB0;
         pA0 += incAk;
         pB0 += incBk;
         *pC0 = rC0_0;
         pC0 += incCm;
         pA0 += incAm;
         pB0 += incBm;
      }
      while(pA0 != stM);
      pC0 += incCn;
      pA0 += incAn;
      pB0 += incBn;
   }
   while(pB0 != stN);
}
#ifdef incAm
   #undef incAm
#endif
#ifdef incAn
   #undef incAn
#endif
#ifdef incAk
   #undef incAk
#endif
#ifdef incBm
   #undef incBm
#endif
#ifdef incBn
   #undef incBn
#endif
#ifdef incBk
   #undef incBk
#endif
#ifdef incCm
   #undef incCm
#endif
#ifdef incCn
   #undef incCn
#endif
#ifdef incCk
   #undef incCk
#endif
#ifdef Mb
   #undef Mb
#endif
#ifdef Nb
   #undef Nb
#endif
#ifdef Kb
   #undef Kb
#endif
static void ATL_cJIK0x0x66TN4x1x66_a1_bX
   (const int M, const int N, const int K, const float alpha, const float * ATL_RESTRICT A, const int lda, const float * ATL_RESTRICT B, const int ldb, const float beta, float * ATL_RESTRICT C, const int ldc)
/*
 * matmul with TA=T, TB=N, MB=0, NB=0, KB=66, 
 * lda=66, ldb=66, ldc=0, mu=4, nu=1, ku=66, pf=0
 * Generated by ATLAS/tune/blas/gemm/emit_mm.c (3.9.23)
 */
{
   const int Mb = (M>>2)<<2;
   #define Nb N
   const float *ca=A, *cb=B;
   float *cc=C;
   const float *stM = A + (((Mb) << 6)+((Mb) << 1));
   const float *stN = B + (((Nb) << 6)+((Nb) << 1));
   #define incAk 66
   const int incAm = 198, incAn = -(((Mb) << 6)+((Mb) << 1));
   #define incBk 66
   const int incBm = -66, incBn = 66;
   #define incCm 8
   const int incCn = (((ldc) << 1)) - (((Mb) << 1));
   float *pC0=C;
   const float *pA0=A;
   const float *pB0=B;
   register int k;
   register float rA0, rA1, rA2, rA3;
   register float rB0;
   register float rC0_0, rC1_0, rC2_0, rC3_0;
   if (pA0 != stM)
   {
      do /* N-loop */
      {
         do /* M-loop */
         {
            rA0 = beta;
            rC0_0 = *pC0;
            rC0_0 *= rA0;
            rC1_0 = pC0[2];
            rC1_0 *= rA0;
            rC2_0 = pC0[4];
            rC2_0 *= rA0;
            rC3_0 = pC0[6];
            rC3_0 *= rA0;
            rA0 = *pA0;
            rB0 = *pB0;
            rC0_0 += rA0 * rB0;
            rA1 = pA0[66];
            rC1_0 += rA1 * rB0;
            rA2 = pA0[132];
            rC2_0 += rA2 * rB0;
            rA3 = pA0[198];
            rC3_0 += rA3 * rB0;
            rA0 = pA0[1];
            rB0 = pB0[1];
            rC0_0 += rA0 * rB0;
            rA1 = pA0[67];
            rC1_0 += rA1 * rB0;
            rA2 = pA0[133];
            rC2_0 += rA2 * rB0;
            rA3 = pA0[199];
            rC3_0 += rA3 * rB0;
            rA0 = pA0[2];
            rB0 = pB0[2];
            rC0_0 += rA0 * rB0;
            rA1 = pA0[68];
            rC1_0 += rA1 * rB0;
            rA2 = pA0[134];
            rC2_0 += rA2 * rB0;
            rA3 = pA0[200];
            rC3_0 += rA3 * rB0;
            rA0 = pA0[3];
            rB0 = pB0[3];
            rC0_0 += rA0 * rB0;
            rA1 = pA0[69];
            rC1_0 += rA1 * rB0;
            rA2 = pA0[135];
            rC2_0 += rA2 * rB0;
            rA3 = pA0[201];
            rC3_0 += rA3 * rB0;
            rA0 = pA0[4];
            rB0 = pB0[4];
            rC0_0 += rA0 * rB0;
            rA1 = pA0[70];
            rC1_0 += rA1 * rB0;
            rA2 = pA0[136];
            rC2_0 += rA2 * rB0;
            rA3 = pA0[202];
            rC3_0 += rA3 * rB0;
            rA0 = pA0[5];
            rB0 = pB0[5];
            rC0_0 += rA0 * rB0;
            rA1 = pA0[71];
            rC1_0 += rA1 * rB0;
            rA2 = pA0[137];
            rC2_0 += rA2 * rB0;
            rA3 = pA0[203];
            rC3_0 += rA3 * rB0;
            rA0 = pA0[6];
            rB0 = pB0[6];
            rC0_0 += rA0 * rB0;
            rA1 = pA0[72];
            rC1_0 += rA1 * rB0;
            rA2 = pA0[138];
            rC2_0 += rA2 * rB0;
            rA3 = pA0[204];
            rC3_0 += rA3 * rB0;
            rA0 = pA0[7];
            rB0 = pB0[7];
            rC0_0 += rA0 * rB0;
            rA1 = pA0[73];
            rC1_0 += rA1 * rB0;
            rA2 = pA0[139];
            rC2_0 += rA2 * rB0;
            rA3 = pA0[205];
            rC3_0 += rA3 * rB0;
            rA0 = pA0[8];
            rB0 = pB0[8];
            rC0_0 += rA0 * rB0;
            rA1 = pA0[74];
            rC1_0 += rA1 * rB0;
            rA2 = pA0[140];
            rC2_0 += rA2 * rB0;
            rA3 = pA0[206];
            rC3_0 += rA3 * rB0;
            rA0 = pA0[9];
            rB0 = pB0[9];
            rC0_0 += rA0 * rB0;
            rA1 = pA0[75];
            rC1_0 += rA1 * rB0;
            rA2 = pA0[141];
            rC2_0 += rA2 * rB0;
            rA3 = pA0[207];
            rC3_0 += rA3 * rB0;
            rA0 = pA0[10];
            rB0 = pB0[10];
            rC0_0 += rA0 * rB0;
            rA1 = pA0[76];
            rC1_0 += rA1 * rB0;
            rA2 = pA0[142];
            rC2_0 += rA2 * rB0;
            rA3 = pA0[208];
            rC3_0 += rA3 * rB0;
            rA0 = pA0[11];
            rB0 = pB0[11];
            rC0_0 += rA0 * rB0;
            rA1 = pA0[77];
            rC1_0 += rA1 * rB0;
            rA2 = pA0[143];
            rC2_0 += rA2 * rB0;
            rA3 = pA0[209];
            rC3_0 += rA3 * rB0;
            rA0 = pA0[12];
            rB0 = pB0[12];
            rC0_0 += rA0 * rB0;
            rA1 = pA0[78];
            rC1_0 += rA1 * rB0;
            rA2 = pA0[144];
            rC2_0 += rA2 * rB0;
            rA3 = pA0[210];
            rC3_0 += rA3 * rB0;
            rA0 = pA0[13];
            rB0 = pB0[13];
            rC0_0 += rA0 * rB0;
            rA1 = pA0[79];
            rC1_0 += rA1 * rB0;
            rA2 = pA0[145];
            rC2_0 += rA2 * rB0;
            rA3 = pA0[211];
            rC3_0 += rA3 * rB0;
            rA0 = pA0[14];
            rB0 = pB0[14];
            rC0_0 += rA0 * rB0;
            rA1 = pA0[80];
            rC1_0 += rA1 * rB0;
            rA2 = pA0[146];
            rC2_0 += rA2 * rB0;
            rA3 = pA0[212];
            rC3_0 += rA3 * rB0;
            rA0 = pA0[15];
            rB0 = pB0[15];
            rC0_0 += rA0 * rB0;
            rA1 = pA0[81];
            rC1_0 += rA1 * rB0;
            rA2 = pA0[147];
            rC2_0 += rA2 * rB0;
            rA3 = pA0[213];
            rC3_0 += rA3 * rB0;
            rA0 = pA0[16];
            rB0 = pB0[16];
            rC0_0 += rA0 * rB0;
            rA1 = pA0[82];
            rC1_0 += rA1 * rB0;
            rA2 = pA0[148];
            rC2_0 += rA2 * rB0;
            rA3 = pA0[214];
            rC3_0 += rA3 * rB0;
            rA0 = pA0[17];
            rB0 = pB0[17];
            rC0_0 += rA0 * rB0;
            rA1 = pA0[83];
            rC1_0 += rA1 * rB0;
            rA2 = pA0[149];
            rC2_0 += rA2 * rB0;
            rA3 = pA0[215];
            rC3_0 += rA3 * rB0;
            rA0 = pA0[18];
            rB0 = pB0[18];
            rC0_0 += rA0 * rB0;
            rA1 = pA0[84];
            rC1_0 += rA1 * rB0;
            rA2 = pA0[150];
            rC2_0 += rA2 * rB0;
            rA3 = pA0[216];
            rC3_0 += rA3 * rB0;
            rA0 = pA0[19];
            rB0 = pB0[19];
            rC0_0 += rA0 * rB0;
            rA1 = pA0[85];
            rC1_0 += rA1 * rB0;
            rA2 = pA0[151];
            rC2_0 += rA2 * rB0;
            rA3 = pA0[217];
            rC3_0 += rA3 * rB0;
            rA0 = pA0[20];
            rB0 = pB0[20];
            rC0_0 += rA0 * rB0;
            rA1 = pA0[86];
            rC1_0 += rA1 * rB0;
            rA2 = pA0[152];
            rC2_0 += rA2 * rB0;
            rA3 = pA0[218];
            rC3_0 += rA3 * rB0;
            rA0 = pA0[21];
            rB0 = pB0[21];
            rC0_0 += rA0 * rB0;
            rA1 = pA0[87];
            rC1_0 += rA1 * rB0;
            rA2 = pA0[153];
            rC2_0 += rA2 * rB0;
            rA3 = pA0[219];
            rC3_0 += rA3 * rB0;
            rA0 = pA0[22];
            rB0 = pB0[22];
            rC0_0 += rA0 * rB0;
            rA1 = pA0[88];
            rC1_0 += rA1 * rB0;
            rA2 = pA0[154];
            rC2_0 += rA2 * rB0;
            rA3 = pA0[220];
            rC3_0 += rA3 * rB0;
            rA0 = pA0[23];
            rB0 = pB0[23];
            rC0_0 += rA0 * rB0;
            rA1 = pA0[89];
            rC1_0 += rA1 * rB0;
            rA2 = pA0[155];
            rC2_0 += rA2 * rB0;
            rA3 = pA0[221];
            rC3_0 += rA3 * rB0;
            rA0 = pA0[24];
            rB0 = pB0[24];
            rC0_0 += rA0 * rB0;
            rA1 = pA0[90];
            rC1_0 += rA1 * rB0;
            rA2 = pA0[156];
            rC2_0 += rA2 * rB0;
            rA3 = pA0[222];
            rC3_0 += rA3 * rB0;
            rA0 = pA0[25];
            rB0 = pB0[25];
            rC0_0 += rA0 * rB0;
            rA1 = pA0[91];
            rC1_0 += rA1 * rB0;
            rA2 = pA0[157];
            rC2_0 += rA2 * rB0;
            rA3 = pA0[223];
            rC3_0 += rA3 * rB0;
            rA0 = pA0[26];
            rB0 = pB0[26];
            rC0_0 += rA0 * rB0;
            rA1 = pA0[92];
            rC1_0 += rA1 * rB0;
            rA2 = pA0[158];
            rC2_0 += rA2 * rB0;
            rA3 = pA0[224];
            rC3_0 += rA3 * rB0;
            rA0 = pA0[27];
            rB0 = pB0[27];
            rC0_0 += rA0 * rB0;
            rA1 = pA0[93];
            rC1_0 += rA1 * rB0;
            rA2 = pA0[159];
            rC2_0 += rA2 * rB0;
            rA3 = pA0[225];
            rC3_0 += rA3 * rB0;
            rA0 = pA0[28];
            rB0 = pB0[28];
            rC0_0 += rA0 * rB0;
            rA1 = pA0[94];
            rC1_0 += rA1 * rB0;
            rA2 = pA0[160];
            rC2_0 += rA2 * rB0;
            rA3 = pA0[226];
            rC3_0 += rA3 * rB0;
            rA0 = pA0[29];
            rB0 = pB0[29];
            rC0_0 += rA0 * rB0;
            rA1 = pA0[95];
            rC1_0 += rA1 * rB0;
            rA2 = pA0[161];
            rC2_0 += rA2 * rB0;
            rA3 = pA0[227];
            rC3_0 += rA3 * rB0;
            rA0 = pA0[30];
            rB0 = pB0[30];
            rC0_0 += rA0 * rB0;
            rA1 = pA0[96];
            rC1_0 += rA1 * rB0;
            rA2 = pA0[162];
            rC2_0 += rA2 * rB0;
            rA3 = pA0[228];
            rC3_0 += rA3 * rB0;
            rA0 = pA0[31];
            rB0 = pB0[31];
            rC0_0 += rA0 * rB0;
            rA1 = pA0[97];
            rC1_0 += rA1 * rB0;
            rA2 = pA0[163];
            rC2_0 += rA2 * rB0;
            rA3 = pA0[229];
            rC3_0 += rA3 * rB0;
            rA0 = pA0[32];
            rB0 = pB0[32];
            rC0_0 += rA0 * rB0;
            rA1 = pA0[98];
            rC1_0 += rA1 * rB0;
            rA2 = pA0[164];
            rC2_0 += rA2 * rB0;
            rA3 = pA0[230];
            rC3_0 += rA3 * rB0;
            rA0 = pA0[33];
            rB0 = pB0[33];
            rC0_0 += rA0 * rB0;
            rA1 = pA0[99];
            rC1_0 += rA1 * rB0;
            rA2 = pA0[165];
            rC2_0 += rA2 * rB0;
            rA3 = pA0[231];
            rC3_0 += rA3 * rB0;
            rA0 = pA0[34];
            rB0 = pB0[34];
            rC0_0 += rA0 * rB0;
            rA1 = pA0[100];
            rC1_0 += rA1 * rB0;
            rA2 = pA0[166];
            rC2_0 += rA2 * rB0;
            rA3 = pA0[232];
            rC3_0 += rA3 * rB0;
            rA0 = pA0[35];
            rB0 = pB0[35];
            rC0_0 += rA0 * rB0;
            rA1 = pA0[101];
            rC1_0 += rA1 * rB0;
            rA2 = pA0[167];
            rC2_0 += rA2 * rB0;
            rA3 = pA0[233];
            rC3_0 += rA3 * rB0;
            rA0 = pA0[36];
            rB0 = pB0[36];
            rC0_0 += rA0 * rB0;
            rA1 = pA0[102];
            rC1_0 += rA1 * rB0;
            rA2 = pA0[168];
            rC2_0 += rA2 * rB0;
            rA3 = pA0[234];
            rC3_0 += rA3 * rB0;
            rA0 = pA0[37];
            rB0 = pB0[37];
            rC0_0 += rA0 * rB0;
            rA1 = pA0[103];
            rC1_0 += rA1 * rB0;
            rA2 = pA0[169];
            rC2_0 += rA2 * rB0;
            rA3 = pA0[235];
            rC3_0 += rA3 * rB0;
            rA0 = pA0[38];
            rB0 = pB0[38];
            rC0_0 += rA0 * rB0;
            rA1 = pA0[104];
            rC1_0 += rA1 * rB0;
            rA2 = pA0[170];
            rC2_0 += rA2 * rB0;
            rA3 = pA0[236];
            rC3_0 += rA3 * rB0;
            rA0 = pA0[39];
            rB0 = pB0[39];
            rC0_0 += rA0 * rB0;
            rA1 = pA0[105];
            rC1_0 += rA1 * rB0;
            rA2 = pA0[171];
            rC2_0 += rA2 * rB0;
            rA3 = pA0[237];
            rC3_0 += rA3 * rB0;
            rA0 = pA0[40];
            rB0 = pB0[40];
            rC0_0 += rA0 * rB0;
            rA1 = pA0[106];
            rC1_0 += rA1 * rB0;
            rA2 = pA0[172];
            rC2_0 += rA2 * rB0;
            rA3 = pA0[238];
            rC3_0 += rA3 * rB0;
            rA0 = pA0[41];
            rB0 = pB0[41];
            rC0_0 += rA0 * rB0;
            rA1 = pA0[107];
            rC1_0 += rA1 * rB0;
            rA2 = pA0[173];
            rC2_0 += rA2 * rB0;
            rA3 = pA0[239];
            rC3_0 += rA3 * rB0;
            rA0 = pA0[42];
            rB0 = pB0[42];
            rC0_0 += rA0 * rB0;
            rA1 = pA0[108];
            rC1_0 += rA1 * rB0;
            rA2 = pA0[174];
            rC2_0 += rA2 * rB0;
            rA3 = pA0[240];
            rC3_0 += rA3 * rB0;
            rA0 = pA0[43];
            rB0 = pB0[43];
            rC0_0 += rA0 * rB0;
            rA1 = pA0[109];
            rC1_0 += rA1 * rB0;
            rA2 = pA0[175];
            rC2_0 += rA2 * rB0;
            rA3 = pA0[241];
            rC3_0 += rA3 * rB0;
            rA0 = pA0[44];
            rB0 = pB0[44];
            rC0_0 += rA0 * rB0;
            rA1 = pA0[110];
            rC1_0 += rA1 * rB0;
            rA2 = pA0[176];
            rC2_0 += rA2 * rB0;
            rA3 = pA0[242];
            rC3_0 += rA3 * rB0;
            rA0 = pA0[45];
            rB0 = pB0[45];
            rC0_0 += rA0 * rB0;
            rA1 = pA0[111];
            rC1_0 += rA1 * rB0;
            rA2 = pA0[177];
            rC2_0 += rA2 * rB0;
            rA3 = pA0[243];
            rC3_0 += rA3 * rB0;
            rA0 = pA0[46];
            rB0 = pB0[46];
            rC0_0 += rA0 * rB0;
            rA1 = pA0[112];
            rC1_0 += rA1 * rB0;
            rA2 = pA0[178];
            rC2_0 += rA2 * rB0;
            rA3 = pA0[244];
            rC3_0 += rA3 * rB0;
            rA0 = pA0[47];
            rB0 = pB0[47];
            rC0_0 += rA0 * rB0;
            rA1 = pA0[113];
            rC1_0 += rA1 * rB0;
            rA2 = pA0[179];
            rC2_0 += rA2 * rB0;
            rA3 = pA0[245];
            rC3_0 += rA3 * rB0;
            rA0 = pA0[48];
            rB0 = pB0[48];
            rC0_0 += rA0 * rB0;
            rA1 = pA0[114];
            rC1_0 += rA1 * rB0;
            rA2 = pA0[180];
            rC2_0 += rA2 * rB0;
            rA3 = pA0[246];
            rC3_0 += rA3 * rB0;
            rA0 = pA0[49];
            rB0 = pB0[49];
            rC0_0 += rA0 * rB0;
            rA1 = pA0[115];
            rC1_0 += rA1 * rB0;
            rA2 = pA0[181];
            rC2_0 += rA2 * rB0;
            rA3 = pA0[247];
            rC3_0 += rA3 * rB0;
            rA0 = pA0[50];
            rB0 = pB0[50];
            rC0_0 += rA0 * rB0;
            rA1 = pA0[116];
            rC1_0 += rA1 * rB0;
            rA2 = pA0[182];
            rC2_0 += rA2 * rB0;
            rA3 = pA0[248];
            rC3_0 += rA3 * rB0;
            rA0 = pA0[51];
            rB0 = pB0[51];
            rC0_0 += rA0 * rB0;
            rA1 = pA0[117];
            rC1_0 += rA1 * rB0;
            rA2 = pA0[183];
            rC2_0 += rA2 * rB0;
            rA3 = pA0[249];
            rC3_0 += rA3 * rB0;
            rA0 = pA0[52];
            rB0 = pB0[52];
            rC0_0 += rA0 * rB0;
            rA1 = pA0[118];
            rC1_0 += rA1 * rB0;
            rA2 = pA0[184];
            rC2_0 += rA2 * rB0;
            rA3 = pA0[250];
            rC3_0 += rA3 * rB0;
            rA0 = pA0[53];
            rB0 = pB0[53];
            rC0_0 += rA0 * rB0;
            rA1 = pA0[119];
            rC1_0 += rA1 * rB0;
            rA2 = pA0[185];
            rC2_0 += rA2 * rB0;
            rA3 = pA0[251];
            rC3_0 += rA3 * rB0;
            rA0 = pA0[54];
            rB0 = pB0[54];
            rC0_0 += rA0 * rB0;
            rA1 = pA0[120];
            rC1_0 += rA1 * rB0;
            rA2 = pA0[186];
            rC2_0 += rA2 * rB0;
            rA3 = pA0[252];
            rC3_0 += rA3 * rB0;
            rA0 = pA0[55];
            rB0 = pB0[55];
            rC0_0 += rA0 * rB0;
            rA1 = pA0[121];
            rC1_0 += rA1 * rB0;
            rA2 = pA0[187];
            rC2_0 += rA2 * rB0;
            rA3 = pA0[253];
            rC3_0 += rA3 * rB0;
            rA0 = pA0[56];
            rB0 = pB0[56];
            rC0_0 += rA0 * rB0;
            rA1 = pA0[122];
            rC1_0 += rA1 * rB0;
            rA2 = pA0[188];
            rC2_0 += rA2 * rB0;
            rA3 = pA0[254];
            rC3_0 += rA3 * rB0;
            rA0 = pA0[57];
            rB0 = pB0[57];
            rC0_0 += rA0 * rB0;
            rA1 = pA0[123];
            rC1_0 += rA1 * rB0;
            rA2 = pA0[189];
            rC2_0 += rA2 * rB0;
            rA3 = pA0[255];
            rC3_0 += rA3 * rB0;
            rA0 = pA0[58];
            rB0 = pB0[58];
            rC0_0 += rA0 * rB0;
            rA1 = pA0[124];
            rC1_0 += rA1 * rB0;
            rA2 = pA0[190];
            rC2_0 += rA2 * rB0;
            rA3 = pA0[256];
            rC3_0 += rA3 * rB0;
            rA0 = pA0[59];
            rB0 = pB0[59];
            rC0_0 += rA0 * rB0;
            rA1 = pA0[125];
            rC1_0 += rA1 * rB0;
            rA2 = pA0[191];
            rC2_0 += rA2 * rB0;
            rA3 = pA0[257];
            rC3_0 += rA3 * rB0;
            rA0 = pA0[60];
            rB0 = pB0[60];
            rC0_0 += rA0 * rB0;
            rA1 = pA0[126];
            rC1_0 += rA1 * rB0;
            rA2 = pA0[192];
            rC2_0 += rA2 * rB0;
            rA3 = pA0[258];
            rC3_0 += rA3 * rB0;
            rA0 = pA0[61];
            rB0 = pB0[61];
            rC0_0 += rA0 * rB0;
            rA1 = pA0[127];
            rC1_0 += rA1 * rB0;
            rA2 = pA0[193];
            rC2_0 += rA2 * rB0;
            rA3 = pA0[259];
            rC3_0 += rA3 * rB0;
            rA0 = pA0[62];
            rB0 = pB0[62];
            rC0_0 += rA0 * rB0;
            rA1 = pA0[128];
            rC1_0 += rA1 * rB0;
            rA2 = pA0[194];
            rC2_0 += rA2 * rB0;
            rA3 = pA0[260];
            rC3_0 += rA3 * rB0;
            rA0 = pA0[63];
            rB0 = pB0[63];
            rC0_0 += rA0 * rB0;
            rA1 = pA0[129];
            rC1_0 += rA1 * rB0;
            rA2 = pA0[195];
            rC2_0 += rA2 * rB0;
            rA3 = pA0[261];
            rC3_0 += rA3 * rB0;
            rA0 = pA0[64];
            rB0 = pB0[64];
            rC0_0 += rA0 * rB0;
            rA1 = pA0[130];
            rC1_0 += rA1 * rB0;
            rA2 = pA0[196];
            rC2_0 += rA2 * rB0;
            rA3 = pA0[262];
            rC3_0 += rA3 * rB0;
            rA0 = pA0[65];
            rB0 = pB0[65];
            rC0_0 += rA0 * rB0;
            rA1 = pA0[131];
            rC1_0 += rA1 * rB0;
            rA2 = pA0[197];
            rC2_0 += rA2 * rB0;
            rA3 = pA0[263];
            rC3_0 += rA3 * rB0;
            pA0 += incAk;
            pB0 += incBk;
            *pC0 = rC0_0;
            pC0[2] = rC1_0;
            pC0[4] = rC2_0;
            pC0[6] = rC3_0;
            pC0 += incCm;
            pA0 += incAm;
            pB0 += incBm;
         }
         while(pA0 != stM);
         pC0 += incCn;
         pA0 += incAn;
         pB0 += incBn;
      }
      while(pB0 != stN);
   }
   if (k=M-Mb)
      ATL_cJIK0x0x66TN1x1x66_a1_bX(k, N, 66, alpha, ca + (((Mb) << 6)+((Mb) << 1)), lda, cb, ldb, beta, cc + (((Mb) << 1)), ldc);
}
#ifdef incAm
   #undef incAm
#endif
#ifdef incAn
   #undef incAn
#endif
#ifdef incAk
   #undef incAk
#endif
#ifdef incBm
   #undef incBm
#endif
#ifdef incBn
   #undef incBn
#endif
#ifdef incBk
   #undef incBk
#endif
#ifdef incCm
   #undef incCm
#endif
#ifdef incCn
   #undef incCn
#endif
#ifdef incCk
   #undef incCk
#endif
#ifdef Mb
   #undef Mb
#endif
#ifdef Nb
   #undef Nb
#endif
#ifdef Kb
   #undef Kb
#endif
#ifndef ATL_RESTRICT
#if defined(__STDC_VERSION__) && (__STDC_VERSION__/100 >= 1999)
   #define ATL_RESTRICT restrict
#else
   #define ATL_RESTRICT
#endif
#endif
static void ATL_cJIK0x0x66TN1x2x66_a1_bX
   (const int M, const int N, const int K, const float alpha, const float * ATL_RESTRICT A, const int lda, const float * ATL_RESTRICT B, const int ldb, const float beta, float * ATL_RESTRICT C, const int ldc)
/*
 * matmul with TA=T, TB=N, MB=0, NB=0, KB=66, 
 * lda=66, ldb=66, ldc=0, mu=1, nu=2, ku=66, pf=0
 * Generated by ATLAS/tune/blas/gemm/emit_mm.c (3.9.23)
 */
{
   #define Mb M
   const int Nb = (N>>1)<<1;
   const float *ca=A, *cb=B;
   float *cc=C;
   const float *stM = A + (((Mb) << 6)+((Mb) << 1));
   const float *stN = B + (((Nb) << 6)+((Nb) << 1));
   #define incAk 66
   const int incAm = 0, incAn = -(((Mb) << 6)+((Mb) << 1));
   #define incBk 66
   const int incBm = -66, incBn = 132;
   #define incCm 2
   const int incCn = (((ldc) << 2)) - (((Mb) << 1));
   float *pC0=C, *pC1=pC0+(((ldc) << 1));
   const float *pA0=A;
   const float *pB0=B;
   register int k;
   register float rA0;
   register float rB0, rB1;
   register float rC0_0, rC0_1;
   if (pB0 != stN)
   {
      do /* N-loop */
      {
         do /* M-loop */
         {
            rA0 = beta;
            rC0_0 = *pC0;
            rC0_0 *= rA0;
            rC0_1 = *pC1;
            rC0_1 *= rA0;
            rA0 = *pA0;
            rB0 = *pB0;
            rC0_0 += rA0 * rB0;
            rB1 = pB0[66];
            rC0_1 += rA0 * rB1;
            rA0 = pA0[1];
            rB0 = pB0[1];
            rC0_0 += rA0 * rB0;
            rB1 = pB0[67];
            rC0_1 += rA0 * rB1;
            rA0 = pA0[2];
            rB0 = pB0[2];
            rC0_0 += rA0 * rB0;
            rB1 = pB0[68];
            rC0_1 += rA0 * rB1;
            rA0 = pA0[3];
            rB0 = pB0[3];
            rC0_0 += rA0 * rB0;
            rB1 = pB0[69];
            rC0_1 += rA0 * rB1;
            rA0 = pA0[4];
            rB0 = pB0[4];
            rC0_0 += rA0 * rB0;
            rB1 = pB0[70];
            rC0_1 += rA0 * rB1;
            rA0 = pA0[5];
            rB0 = pB0[5];
            rC0_0 += rA0 * rB0;
            rB1 = pB0[71];
            rC0_1 += rA0 * rB1;
            rA0 = pA0[6];
            rB0 = pB0[6];
            rC0_0 += rA0 * rB0;
            rB1 = pB0[72];
            rC0_1 += rA0 * rB1;
            rA0 = pA0[7];
            rB0 = pB0[7];
            rC0_0 += rA0 * rB0;
            rB1 = pB0[73];
            rC0_1 += rA0 * rB1;
            rA0 = pA0[8];
            rB0 = pB0[8];
            rC0_0 += rA0 * rB0;
            rB1 = pB0[74];
            rC0_1 += rA0 * rB1;
            rA0 = pA0[9];
            rB0 = pB0[9];
            rC0_0 += rA0 * rB0;
            rB1 = pB0[75];
            rC0_1 += rA0 * rB1;
            rA0 = pA0[10];
            rB0 = pB0[10];
            rC0_0 += rA0 * rB0;
            rB1 = pB0[76];
            rC0_1 += rA0 * rB1;
            rA0 = pA0[11];
            rB0 = pB0[11];
            rC0_0 += rA0 * rB0;
            rB1 = pB0[77];
            rC0_1 += rA0 * rB1;
            rA0 = pA0[12];
            rB0 = pB0[12];
            rC0_0 += rA0 * rB0;
            rB1 = pB0[78];
            rC0_1 += rA0 * rB1;
            rA0 = pA0[13];
            rB0 = pB0[13];
            rC0_0 += rA0 * rB0;
            rB1 = pB0[79];
            rC0_1 += rA0 * rB1;
            rA0 = pA0[14];
            rB0 = pB0[14];
            rC0_0 += rA0 * rB0;
            rB1 = pB0[80];
            rC0_1 += rA0 * rB1;
            rA0 = pA0[15];
            rB0 = pB0[15];
            rC0_0 += rA0 * rB0;
            rB1 = pB0[81];
            rC0_1 += rA0 * rB1;
            rA0 = pA0[16];
            rB0 = pB0[16];
            rC0_0 += rA0 * rB0;
            rB1 = pB0[82];
            rC0_1 += rA0 * rB1;
            rA0 = pA0[17];
            rB0 = pB0[17];
            rC0_0 += rA0 * rB0;
            rB1 = pB0[83];
            rC0_1 += rA0 * rB1;
            rA0 = pA0[18];
            rB0 = pB0[18];
            rC0_0 += rA0 * rB0;
            rB1 = pB0[84];
            rC0_1 += rA0 * rB1;
            rA0 = pA0[19];
            rB0 = pB0[19];
            rC0_0 += rA0 * rB0;
            rB1 = pB0[85];
            rC0_1 += rA0 * rB1;
            rA0 = pA0[20];
            rB0 = pB0[20];
            rC0_0 += rA0 * rB0;
            rB1 = pB0[86];
            rC0_1 += rA0 * rB1;
            rA0 = pA0[21];
            rB0 = pB0[21];
            rC0_0 += rA0 * rB0;
            rB1 = pB0[87];
            rC0_1 += rA0 * rB1;
            rA0 = pA0[22];
            rB0 = pB0[22];
            rC0_0 += rA0 * rB0;
            rB1 = pB0[88];
            rC0_1 += rA0 * rB1;
            rA0 = pA0[23];
            rB0 = pB0[23];
            rC0_0 += rA0 * rB0;
            rB1 = pB0[89];
            rC0_1 += rA0 * rB1;
            rA0 = pA0[24];
            rB0 = pB0[24];
            rC0_0 += rA0 * rB0;
            rB1 = pB0[90];
            rC0_1 += rA0 * rB1;
            rA0 = pA0[25];
            rB0 = pB0[25];
            rC0_0 += rA0 * rB0;
            rB1 = pB0[91];
            rC0_1 += rA0 * rB1;
            rA0 = pA0[26];
            rB0 = pB0[26];
            rC0_0 += rA0 * rB0;
            rB1 = pB0[92];
            rC0_1 += rA0 * rB1;
            rA0 = pA0[27];
            rB0 = pB0[27];
            rC0_0 += rA0 * rB0;
            rB1 = pB0[93];
            rC0_1 += rA0 * rB1;
            rA0 = pA0[28];
            rB0 = pB0[28];
            rC0_0 += rA0 * rB0;
            rB1 = pB0[94];
            rC0_1 += rA0 * rB1;
            rA0 = pA0[29];
            rB0 = pB0[29];
            rC0_0 += rA0 * rB0;
            rB1 = pB0[95];
            rC0_1 += rA0 * rB1;
            rA0 = pA0[30];
            rB0 = pB0[30];
            rC0_0 += rA0 * rB0;
            rB1 = pB0[96];
            rC0_1 += rA0 * rB1;
            rA0 = pA0[31];
            rB0 = pB0[31];
            rC0_0 += rA0 * rB0;
            rB1 = pB0[97];
            rC0_1 += rA0 * rB1;
            rA0 = pA0[32];
            rB0 = pB0[32];
            rC0_0 += rA0 * rB0;
            rB1 = pB0[98];
            rC0_1 += rA0 * rB1;
            rA0 = pA0[33];
            rB0 = pB0[33];
            rC0_0 += rA0 * rB0;
            rB1 = pB0[99];
            rC0_1 += rA0 * rB1;
            rA0 = pA0[34];
            rB0 = pB0[34];
            rC0_0 += rA0 * rB0;
            rB1 = pB0[100];
            rC0_1 += rA0 * rB1;
            rA0 = pA0[35];
            rB0 = pB0[35];
            rC0_0 += rA0 * rB0;
            rB1 = pB0[101];
            rC0_1 += rA0 * rB1;
            rA0 = pA0[36];
            rB0 = pB0[36];
            rC0_0 += rA0 * rB0;
            rB1 = pB0[102];
            rC0_1 += rA0 * rB1;
            rA0 = pA0[37];
            rB0 = pB0[37];
            rC0_0 += rA0 * rB0;
            rB1 = pB0[103];
            rC0_1 += rA0 * rB1;
            rA0 = pA0[38];
            rB0 = pB0[38];
            rC0_0 += rA0 * rB0;
            rB1 = pB0[104];
            rC0_1 += rA0 * rB1;
            rA0 = pA0[39];
            rB0 = pB0[39];
            rC0_0 += rA0 * rB0;
            rB1 = pB0[105];
            rC0_1 += rA0 * rB1;
            rA0 = pA0[40];
            rB0 = pB0[40];
            rC0_0 += rA0 * rB0;
            rB1 = pB0[106];
            rC0_1 += rA0 * rB1;
            rA0 = pA0[41];
            rB0 = pB0[41];
            rC0_0 += rA0 * rB0;
            rB1 = pB0[107];
            rC0_1 += rA0 * rB1;
            rA0 = pA0[42];
            rB0 = pB0[42];
            rC0_0 += rA0 * rB0;
            rB1 = pB0[108];
            rC0_1 += rA0 * rB1;
            rA0 = pA0[43];
            rB0 = pB0[43];
            rC0_0 += rA0 * rB0;
            rB1 = pB0[109];
            rC0_1 += rA0 * rB1;
            rA0 = pA0[44];
            rB0 = pB0[44];
            rC0_0 += rA0 * rB0;
            rB1 = pB0[110];
            rC0_1 += rA0 * rB1;
            rA0 = pA0[45];
            rB0 = pB0[45];
            rC0_0 += rA0 * rB0;
            rB1 = pB0[111];
            rC0_1 += rA0 * rB1;
            rA0 = pA0[46];
            rB0 = pB0[46];
            rC0_0 += rA0 * rB0;
            rB1 = pB0[112];
            rC0_1 += rA0 * rB1;
            rA0 = pA0[47];
            rB0 = pB0[47];
            rC0_0 += rA0 * rB0;
            rB1 = pB0[113];
            rC0_1 += rA0 * rB1;
            rA0 = pA0[48];
            rB0 = pB0[48];
            rC0_0 += rA0 * rB0;
            rB1 = pB0[114];
            rC0_1 += rA0 * rB1;
            rA0 = pA0[49];
            rB0 = pB0[49];
            rC0_0 += rA0 * rB0;
            rB1 = pB0[115];
            rC0_1 += rA0 * rB1;
            rA0 = pA0[50];
            rB0 = pB0[50];
            rC0_0 += rA0 * rB0;
            rB1 = pB0[116];
            rC0_1 += rA0 * rB1;
            rA0 = pA0[51];
            rB0 = pB0[51];
            rC0_0 += rA0 * rB0;
            rB1 = pB0[117];
            rC0_1 += rA0 * rB1;
            rA0 = pA0[52];
            rB0 = pB0[52];
            rC0_0 += rA0 * rB0;
            rB1 = pB0[118];
            rC0_1 += rA0 * rB1;
            rA0 = pA0[53];
            rB0 = pB0[53];
            rC0_0 += rA0 * rB0;
            rB1 = pB0[119];
            rC0_1 += rA0 * rB1;
            rA0 = pA0[54];
            rB0 = pB0[54];
            rC0_0 += rA0 * rB0;
            rB1 = pB0[120];
            rC0_1 += rA0 * rB1;
            rA0 = pA0[55];
            rB0 = pB0[55];
            rC0_0 += rA0 * rB0;
            rB1 = pB0[121];
            rC0_1 += rA0 * rB1;
            rA0 = pA0[56];
            rB0 = pB0[56];
            rC0_0 += rA0 * rB0;
            rB1 = pB0[122];
            rC0_1 += rA0 * rB1;
            rA0 = pA0[57];
            rB0 = pB0[57];
            rC0_0 += rA0 * rB0;
            rB1 = pB0[123];
            rC0_1 += rA0 * rB1;
            rA0 = pA0[58];
            rB0 = pB0[58];
            rC0_0 += rA0 * rB0;
            rB1 = pB0[124];
            rC0_1 += rA0 * rB1;
            rA0 = pA0[59];
            rB0 = pB0[59];
            rC0_0 += rA0 * rB0;
            rB1 = pB0[125];
            rC0_1 += rA0 * rB1;
            rA0 = pA0[60];
            rB0 = pB0[60];
            rC0_0 += rA0 * rB0;
            rB1 = pB0[126];
            rC0_1 += rA0 * rB1;
            rA0 = pA0[61];
            rB0 = pB0[61];
            rC0_0 += rA0 * rB0;
            rB1 = pB0[127];
            rC0_1 += rA0 * rB1;
            rA0 = pA0[62];
            rB0 = pB0[62];
            rC0_0 += rA0 * rB0;
            rB1 = pB0[128];
            rC0_1 += rA0 * rB1;
            rA0 = pA0[63];
            rB0 = pB0[63];
            rC0_0 += rA0 * rB0;
            rB1 = pB0[129];
            rC0_1 += rA0 * rB1;
            rA0 = pA0[64];
            rB0 = pB0[64];
            rC0_0 += rA0 * rB0;
            rB1 = pB0[130];
            rC0_1 += rA0 * rB1;
            rA0 = pA0[65];
            rB0 = pB0[65];
            rC0_0 += rA0 * rB0;
            rB1 = pB0[131];
            rC0_1 += rA0 * rB1;
            pA0 += incAk;
            pB0 += incBk;
            *pC0 = rC0_0;
            *pC1 = rC0_1;
            pC0 += incCm;
            pC1 += incCm;
            pA0 += incAm;
            pB0 += incBm;
         }
         while(pA0 != stM);
         pC0 += incCn;
         pC1 += incCn;
         pA0 += incAn;
         pB0 += incBn;
      }
      while(pB0 != stN);
   }
   if (k=N-Nb)
      ATL_cJIK0x0x66TN1x1x66_a1_bX(M, k, 66, alpha, ca, lda, cb + (((Nb) << 6)+((Nb) << 1)), ldb, beta, cc + (((Nb*ldc) << 1)), ldc);
}
#ifdef incAm
   #undef incAm
#endif
#ifdef incAn
   #undef incAn
#endif
#ifdef incAk
   #undef incAk
#endif
#ifdef incBm
   #undef incBm
#endif
#ifdef incBn
   #undef incBn
#endif
#ifdef incBk
   #undef incBk
#endif
#ifdef incCm
   #undef incCm
#endif
#ifdef incCn
   #undef incCn
#endif
#ifdef incCk
   #undef incCk
#endif
#ifdef Mb
   #undef Mb
#endif
#ifdef Nb
   #undef Nb
#endif
#ifdef Kb
   #undef Kb
#endif
void ATL_cJIK0x0x66TN66x66x0_a1_bX
   (const int M, const int N, const int K, const float alpha, const float * ATL_RESTRICT A, const int lda, const float * ATL_RESTRICT B, const int ldb, const float beta, float * ATL_RESTRICT C, const int ldc)
/*
 * matmul with TA=T, TB=N, MB=0, NB=0, KB=66, 
 * lda=66, ldb=66, ldc=0, mu=4, nu=2, ku=66, pf=0
 * Generated by ATLAS/tune/blas/gemm/emit_mm.c (3.9.23)
 */
{
   const int Mb = (M>>2)<<2;
   const int Nb = (N>>1)<<1;
   const float *ca=A, *cb=B;
   float *cc=C;
   const float *stM = A + (((Mb) << 6)+((Mb) << 1));
   const float *stN = B + (((Nb) << 6)+((Nb) << 1));
   #define incAk 66
   const int incAm = 198, incAn = -(((Mb) << 6)+((Mb) << 1));
   #define incBk 66
   const int incBm = -66, incBn = 132;
   #define incCm 8
   const int incCn = (((ldc) << 2)) - (((Mb) << 1));
   float *pC0=C, *pC1=pC0+(((ldc) << 1));
   const float *pA0=A;
   const float *pB0=B;
   register int k;
   register float rA0, rA1, rA2, rA3;
   register float rB0, rB1;
   register float rC0_0, rC1_0, rC2_0, rC3_0, rC0_1, rC1_1, rC2_1, rC3_1;
   if (pA0 != stM)
   {
      if (pB0 != stN)
      {
         do /* N-loop */
         {
            do /* M-loop */
            {
               rA0 = beta;
               rC0_0 = *pC0;
               rC0_0 *= rA0;
               rC1_0 = pC0[2];
               rC1_0 *= rA0;
               rC2_0 = pC0[4];
               rC2_0 *= rA0;
               rC3_0 = pC0[6];
               rC3_0 *= rA0;
               rC0_1 = *pC1;
               rC0_1 *= rA0;
               rC1_1 = pC1[2];
               rC1_1 *= rA0;
               rC2_1 = pC1[4];
               rC2_1 *= rA0;
               rC3_1 = pC1[6];
               rC3_1 *= rA0;
               rA0 = *pA0;
               rB0 = *pB0;
               rC0_0 += rA0 * rB0;
               rA1 = pA0[66];
               rC1_0 += rA1 * rB0;
               rA2 = pA0[132];
               rC2_0 += rA2 * rB0;
               rA3 = pA0[198];
               rC3_0 += rA3 * rB0;
               rB1 = pB0[66];
               rC0_1 += rA0 * rB1;
               rC1_1 += rA1 * rB1;
               rC2_1 += rA2 * rB1;
               rC3_1 += rA3 * rB1;
               rA0 = pA0[1];
               rB0 = pB0[1];
               rC0_0 += rA0 * rB0;
               rA1 = pA0[67];
               rC1_0 += rA1 * rB0;
               rA2 = pA0[133];
               rC2_0 += rA2 * rB0;
               rA3 = pA0[199];
               rC3_0 += rA3 * rB0;
               rB1 = pB0[67];
               rC0_1 += rA0 * rB1;
               rC1_1 += rA1 * rB1;
               rC2_1 += rA2 * rB1;
               rC3_1 += rA3 * rB1;
               rA0 = pA0[2];
               rB0 = pB0[2];
               rC0_0 += rA0 * rB0;
               rA1 = pA0[68];
               rC1_0 += rA1 * rB0;
               rA2 = pA0[134];
               rC2_0 += rA2 * rB0;
               rA3 = pA0[200];
               rC3_0 += rA3 * rB0;
               rB1 = pB0[68];
               rC0_1 += rA0 * rB1;
               rC1_1 += rA1 * rB1;
               rC2_1 += rA2 * rB1;
               rC3_1 += rA3 * rB1;
               rA0 = pA0[3];
               rB0 = pB0[3];
               rC0_0 += rA0 * rB0;
               rA1 = pA0[69];
               rC1_0 += rA1 * rB0;
               rA2 = pA0[135];
               rC2_0 += rA2 * rB0;
               rA3 = pA0[201];
               rC3_0 += rA3 * rB0;
               rB1 = pB0[69];
               rC0_1 += rA0 * rB1;
               rC1_1 += rA1 * rB1;
               rC2_1 += rA2 * rB1;
               rC3_1 += rA3 * rB1;
               rA0 = pA0[4];
               rB0 = pB0[4];
               rC0_0 += rA0 * rB0;
               rA1 = pA0[70];
               rC1_0 += rA1 * rB0;
               rA2 = pA0[136];
               rC2_0 += rA2 * rB0;
               rA3 = pA0[202];
               rC3_0 += rA3 * rB0;
               rB1 = pB0[70];
               rC0_1 += rA0 * rB1;
               rC1_1 += rA1 * rB1;
               rC2_1 += rA2 * rB1;
               rC3_1 += rA3 * rB1;
               rA0 = pA0[5];
               rB0 = pB0[5];
               rC0_0 += rA0 * rB0;
               rA1 = pA0[71];
               rC1_0 += rA1 * rB0;
               rA2 = pA0[137];
               rC2_0 += rA2 * rB0;
               rA3 = pA0[203];
               rC3_0 += rA3 * rB0;
               rB1 = pB0[71];
               rC0_1 += rA0 * rB1;
               rC1_1 += rA1 * rB1;
               rC2_1 += rA2 * rB1;
               rC3_1 += rA3 * rB1;
               rA0 = pA0[6];
               rB0 = pB0[6];
               rC0_0 += rA0 * rB0;
               rA1 = pA0[72];
               rC1_0 += rA1 * rB0;
               rA2 = pA0[138];
               rC2_0 += rA2 * rB0;
               rA3 = pA0[204];
               rC3_0 += rA3 * rB0;
               rB1 = pB0[72];
               rC0_1 += rA0 * rB1;
               rC1_1 += rA1 * rB1;
               rC2_1 += rA2 * rB1;
               rC3_1 += rA3 * rB1;
               rA0 = pA0[7];
               rB0 = pB0[7];
               rC0_0 += rA0 * rB0;
               rA1 = pA0[73];
               rC1_0 += rA1 * rB0;
               rA2 = pA0[139];
               rC2_0 += rA2 * rB0;
               rA3 = pA0[205];
               rC3_0 += rA3 * rB0;
               rB1 = pB0[73];
               rC0_1 += rA0 * rB1;
               rC1_1 += rA1 * rB1;
               rC2_1 += rA2 * rB1;
               rC3_1 += rA3 * rB1;
               rA0 = pA0[8];
               rB0 = pB0[8];
               rC0_0 += rA0 * rB0;
               rA1 = pA0[74];
               rC1_0 += rA1 * rB0;
               rA2 = pA0[140];
               rC2_0 += rA2 * rB0;
               rA3 = pA0[206];
               rC3_0 += rA3 * rB0;
               rB1 = pB0[74];
               rC0_1 += rA0 * rB1;
               rC1_1 += rA1 * rB1;
               rC2_1 += rA2 * rB1;
               rC3_1 += rA3 * rB1;
               rA0 = pA0[9];
               rB0 = pB0[9];
               rC0_0 += rA0 * rB0;
               rA1 = pA0[75];
               rC1_0 += rA1 * rB0;
               rA2 = pA0[141];
               rC2_0 += rA2 * rB0;
               rA3 = pA0[207];
               rC3_0 += rA3 * rB0;
               rB1 = pB0[75];
               rC0_1 += rA0 * rB1;
               rC1_1 += rA1 * rB1;
               rC2_1 += rA2 * rB1;
               rC3_1 += rA3 * rB1;
               rA0 = pA0[10];
               rB0 = pB0[10];
               rC0_0 += rA0 * rB0;
               rA1 = pA0[76];
               rC1_0 += rA1 * rB0;
               rA2 = pA0[142];
               rC2_0 += rA2 * rB0;
               rA3 = pA0[208];
               rC3_0 += rA3 * rB0;
               rB1 = pB0[76];
               rC0_1 += rA0 * rB1;
               rC1_1 += rA1 * rB1;
               rC2_1 += rA2 * rB1;
               rC3_1 += rA3 * rB1;
               rA0 = pA0[11];
               rB0 = pB0[11];
               rC0_0 += rA0 * rB0;
               rA1 = pA0[77];
               rC1_0 += rA1 * rB0;
               rA2 = pA0[143];
               rC2_0 += rA2 * rB0;
               rA3 = pA0[209];
               rC3_0 += rA3 * rB0;
               rB1 = pB0[77];
               rC0_1 += rA0 * rB1;
               rC1_1 += rA1 * rB1;
               rC2_1 += rA2 * rB1;
               rC3_1 += rA3 * rB1;
               rA0 = pA0[12];
               rB0 = pB0[12];
               rC0_0 += rA0 * rB0;
               rA1 = pA0[78];
               rC1_0 += rA1 * rB0;
               rA2 = pA0[144];
               rC2_0 += rA2 * rB0;
               rA3 = pA0[210];
               rC3_0 += rA3 * rB0;
               rB1 = pB0[78];
               rC0_1 += rA0 * rB1;
               rC1_1 += rA1 * rB1;
               rC2_1 += rA2 * rB1;
               rC3_1 += rA3 * rB1;
               rA0 = pA0[13];
               rB0 = pB0[13];
               rC0_0 += rA0 * rB0;
               rA1 = pA0[79];
               rC1_0 += rA1 * rB0;
               rA2 = pA0[145];
               rC2_0 += rA2 * rB0;
               rA3 = pA0[211];
               rC3_0 += rA3 * rB0;
               rB1 = pB0[79];
               rC0_1 += rA0 * rB1;
               rC1_1 += rA1 * rB1;
               rC2_1 += rA2 * rB1;
               rC3_1 += rA3 * rB1;
               rA0 = pA0[14];
               rB0 = pB0[14];
               rC0_0 += rA0 * rB0;
               rA1 = pA0[80];
               rC1_0 += rA1 * rB0;
               rA2 = pA0[146];
               rC2_0 += rA2 * rB0;
               rA3 = pA0[212];
               rC3_0 += rA3 * rB0;
               rB1 = pB0[80];
               rC0_1 += rA0 * rB1;
               rC1_1 += rA1 * rB1;
               rC2_1 += rA2 * rB1;
               rC3_1 += rA3 * rB1;
               rA0 = pA0[15];
               rB0 = pB0[15];
               rC0_0 += rA0 * rB0;
               rA1 = pA0[81];
               rC1_0 += rA1 * rB0;
               rA2 = pA0[147];
               rC2_0 += rA2 * rB0;
               rA3 = pA0[213];
               rC3_0 += rA3 * rB0;
               rB1 = pB0[81];
               rC0_1 += rA0 * rB1;
               rC1_1 += rA1 * rB1;
               rC2_1 += rA2 * rB1;
               rC3_1 += rA3 * rB1;
               rA0 = pA0[16];
               rB0 = pB0[16];
               rC0_0 += rA0 * rB0;
               rA1 = pA0[82];
               rC1_0 += rA1 * rB0;
               rA2 = pA0[148];
               rC2_0 += rA2 * rB0;
               rA3 = pA0[214];
               rC3_0 += rA3 * rB0;
               rB1 = pB0[82];
               rC0_1 += rA0 * rB1;
               rC1_1 += rA1 * rB1;
               rC2_1 += rA2 * rB1;
               rC3_1 += rA3 * rB1;
               rA0 = pA0[17];
               rB0 = pB0[17];
               rC0_0 += rA0 * rB0;
               rA1 = pA0[83];
               rC1_0 += rA1 * rB0;
               rA2 = pA0[149];
               rC2_0 += rA2 * rB0;
               rA3 = pA0[215];
               rC3_0 += rA3 * rB0;
               rB1 = pB0[83];
               rC0_1 += rA0 * rB1;
               rC1_1 += rA1 * rB1;
               rC2_1 += rA2 * rB1;
               rC3_1 += rA3 * rB1;
               rA0 = pA0[18];
               rB0 = pB0[18];
               rC0_0 += rA0 * rB0;
               rA1 = pA0[84];
               rC1_0 += rA1 * rB0;
               rA2 = pA0[150];
               rC2_0 += rA2 * rB0;
               rA3 = pA0[216];
               rC3_0 += rA3 * rB0;
               rB1 = pB0[84];
               rC0_1 += rA0 * rB1;
               rC1_1 += rA1 * rB1;
               rC2_1 += rA2 * rB1;
               rC3_1 += rA3 * rB1;
               rA0 = pA0[19];
               rB0 = pB0[19];
               rC0_0 += rA0 * rB0;
               rA1 = pA0[85];
               rC1_0 += rA1 * rB0;
               rA2 = pA0[151];
               rC2_0 += rA2 * rB0;
               rA3 = pA0[217];
               rC3_0 += rA3 * rB0;
               rB1 = pB0[85];
               rC0_1 += rA0 * rB1;
               rC1_1 += rA1 * rB1;
               rC2_1 += rA2 * rB1;
               rC3_1 += rA3 * rB1;
               rA0 = pA0[20];
               rB0 = pB0[20];
               rC0_0 += rA0 * rB0;
               rA1 = pA0[86];
               rC1_0 += rA1 * rB0;
               rA2 = pA0[152];
               rC2_0 += rA2 * rB0;
               rA3 = pA0[218];
               rC3_0 += rA3 * rB0;
               rB1 = pB0[86];
               rC0_1 += rA0 * rB1;
               rC1_1 += rA1 * rB1;
               rC2_1 += rA2 * rB1;
               rC3_1 += rA3 * rB1;
               rA0 = pA0[21];
               rB0 = pB0[21];
               rC0_0 += rA0 * rB0;
               rA1 = pA0[87];
               rC1_0 += rA1 * rB0;
               rA2 = pA0[153];
               rC2_0 += rA2 * rB0;
               rA3 = pA0[219];
               rC3_0 += rA3 * rB0;
               rB1 = pB0[87];
               rC0_1 += rA0 * rB1;
               rC1_1 += rA1 * rB1;
               rC2_1 += rA2 * rB1;
               rC3_1 += rA3 * rB1;
               rA0 = pA0[22];
               rB0 = pB0[22];
               rC0_0 += rA0 * rB0;
               rA1 = pA0[88];
               rC1_0 += rA1 * rB0;
               rA2 = pA0[154];
               rC2_0 += rA2 * rB0;
               rA3 = pA0[220];
               rC3_0 += rA3 * rB0;
               rB1 = pB0[88];
               rC0_1 += rA0 * rB1;
               rC1_1 += rA1 * rB1;
               rC2_1 += rA2 * rB1;
               rC3_1 += rA3 * rB1;
               rA0 = pA0[23];
               rB0 = pB0[23];
               rC0_0 += rA0 * rB0;
               rA1 = pA0[89];
               rC1_0 += rA1 * rB0;
               rA2 = pA0[155];
               rC2_0 += rA2 * rB0;
               rA3 = pA0[221];
               rC3_0 += rA3 * rB0;
               rB1 = pB0[89];
               rC0_1 += rA0 * rB1;
               rC1_1 += rA1 * rB1;
               rC2_1 += rA2 * rB1;
               rC3_1 += rA3 * rB1;
               rA0 = pA0[24];
               rB0 = pB0[24];
               rC0_0 += rA0 * rB0;
               rA1 = pA0[90];
               rC1_0 += rA1 * rB0;
               rA2 = pA0[156];
               rC2_0 += rA2 * rB0;
               rA3 = pA0[222];
               rC3_0 += rA3 * rB0;
               rB1 = pB0[90];
               rC0_1 += rA0 * rB1;
               rC1_1 += rA1 * rB1;
               rC2_1 += rA2 * rB1;
               rC3_1 += rA3 * rB1;
               rA0 = pA0[25];
               rB0 = pB0[25];
               rC0_0 += rA0 * rB0;
               rA1 = pA0[91];
               rC1_0 += rA1 * rB0;
               rA2 = pA0[157];
               rC2_0 += rA2 * rB0;
               rA3 = pA0[223];
               rC3_0 += rA3 * rB0;
               rB1 = pB0[91];
               rC0_1 += rA0 * rB1;
               rC1_1 += rA1 * rB1;
               rC2_1 += rA2 * rB1;
               rC3_1 += rA3 * rB1;
               rA0 = pA0[26];
               rB0 = pB0[26];
               rC0_0 += rA0 * rB0;
               rA1 = pA0[92];
               rC1_0 += rA1 * rB0;
               rA2 = pA0[158];
               rC2_0 += rA2 * rB0;
               rA3 = pA0[224];
               rC3_0 += rA3 * rB0;
               rB1 = pB0[92];
               rC0_1 += rA0 * rB1;
               rC1_1 += rA1 * rB1;
               rC2_1 += rA2 * rB1;
               rC3_1 += rA3 * rB1;
               rA0 = pA0[27];
               rB0 = pB0[27];
               rC0_0 += rA0 * rB0;
               rA1 = pA0[93];
               rC1_0 += rA1 * rB0;
               rA2 = pA0[159];
               rC2_0 += rA2 * rB0;
               rA3 = pA0[225];
               rC3_0 += rA3 * rB0;
               rB1 = pB0[93];
               rC0_1 += rA0 * rB1;
               rC1_1 += rA1 * rB1;
               rC2_1 += rA2 * rB1;
               rC3_1 += rA3 * rB1;
               rA0 = pA0[28];
               rB0 = pB0[28];
               rC0_0 += rA0 * rB0;
               rA1 = pA0[94];
               rC1_0 += rA1 * rB0;
               rA2 = pA0[160];
               rC2_0 += rA2 * rB0;
               rA3 = pA0[226];
               rC3_0 += rA3 * rB0;
               rB1 = pB0[94];
               rC0_1 += rA0 * rB1;
               rC1_1 += rA1 * rB1;
               rC2_1 += rA2 * rB1;
               rC3_1 += rA3 * rB1;
               rA0 = pA0[29];
               rB0 = pB0[29];
               rC0_0 += rA0 * rB0;
               rA1 = pA0[95];
               rC1_0 += rA1 * rB0;
               rA2 = pA0[161];
               rC2_0 += rA2 * rB0;
               rA3 = pA0[227];
               rC3_0 += rA3 * rB0;
               rB1 = pB0[95];
               rC0_1 += rA0 * rB1;
               rC1_1 += rA1 * rB1;
               rC2_1 += rA2 * rB1;
               rC3_1 += rA3 * rB1;
               rA0 = pA0[30];
               rB0 = pB0[30];
               rC0_0 += rA0 * rB0;
               rA1 = pA0[96];
               rC1_0 += rA1 * rB0;
               rA2 = pA0[162];
               rC2_0 += rA2 * rB0;
               rA3 = pA0[228];
               rC3_0 += rA3 * rB0;
               rB1 = pB0[96];
               rC0_1 += rA0 * rB1;
               rC1_1 += rA1 * rB1;
               rC2_1 += rA2 * rB1;
               rC3_1 += rA3 * rB1;
               rA0 = pA0[31];
               rB0 = pB0[31];
               rC0_0 += rA0 * rB0;
               rA1 = pA0[97];
               rC1_0 += rA1 * rB0;
               rA2 = pA0[163];
               rC2_0 += rA2 * rB0;
               rA3 = pA0[229];
               rC3_0 += rA3 * rB0;
               rB1 = pB0[97];
               rC0_1 += rA0 * rB1;
               rC1_1 += rA1 * rB1;
               rC2_1 += rA2 * rB1;
               rC3_1 += rA3 * rB1;
               rA0 = pA0[32];
               rB0 = pB0[32];
               rC0_0 += rA0 * rB0;
               rA1 = pA0[98];
               rC1_0 += rA1 * rB0;
               rA2 = pA0[164];
               rC2_0 += rA2 * rB0;
               rA3 = pA0[230];
               rC3_0 += rA3 * rB0;
               rB1 = pB0[98];
               rC0_1 += rA0 * rB1;
               rC1_1 += rA1 * rB1;
               rC2_1 += rA2 * rB1;
               rC3_1 += rA3 * rB1;
               rA0 = pA0[33];
               rB0 = pB0[33];
               rC0_0 += rA0 * rB0;
               rA1 = pA0[99];
               rC1_0 += rA1 * rB0;
               rA2 = pA0[165];
               rC2_0 += rA2 * rB0;
               rA3 = pA0[231];
               rC3_0 += rA3 * rB0;
               rB1 = pB0[99];
               rC0_1 += rA0 * rB1;
               rC1_1 += rA1 * rB1;
               rC2_1 += rA2 * rB1;
               rC3_1 += rA3 * rB1;
               rA0 = pA0[34];
               rB0 = pB0[34];
               rC0_0 += rA0 * rB0;
               rA1 = pA0[100];
               rC1_0 += rA1 * rB0;
               rA2 = pA0[166];
               rC2_0 += rA2 * rB0;
               rA3 = pA0[232];
               rC3_0 += rA3 * rB0;
               rB1 = pB0[100];
               rC0_1 += rA0 * rB1;
               rC1_1 += rA1 * rB1;
               rC2_1 += rA2 * rB1;
               rC3_1 += rA3 * rB1;
               rA0 = pA0[35];
               rB0 = pB0[35];
               rC0_0 += rA0 * rB0;
               rA1 = pA0[101];
               rC1_0 += rA1 * rB0;
               rA2 = pA0[167];
               rC2_0 += rA2 * rB0;
               rA3 = pA0[233];
               rC3_0 += rA3 * rB0;
               rB1 = pB0[101];
               rC0_1 += rA0 * rB1;
               rC1_1 += rA1 * rB1;
               rC2_1 += rA2 * rB1;
               rC3_1 += rA3 * rB1;
               rA0 = pA0[36];
               rB0 = pB0[36];
               rC0_0 += rA0 * rB0;
               rA1 = pA0[102];
               rC1_0 += rA1 * rB0;
               rA2 = pA0[168];
               rC2_0 += rA2 * rB0;
               rA3 = pA0[234];
               rC3_0 += rA3 * rB0;
               rB1 = pB0[102];
               rC0_1 += rA0 * rB1;
               rC1_1 += rA1 * rB1;
               rC2_1 += rA2 * rB1;
               rC3_1 += rA3 * rB1;
               rA0 = pA0[37];
               rB0 = pB0[37];
               rC0_0 += rA0 * rB0;
               rA1 = pA0[103];
               rC1_0 += rA1 * rB0;
               rA2 = pA0[169];
               rC2_0 += rA2 * rB0;
               rA3 = pA0[235];
               rC3_0 += rA3 * rB0;
               rB1 = pB0[103];
               rC0_1 += rA0 * rB1;
               rC1_1 += rA1 * rB1;
               rC2_1 += rA2 * rB1;
               rC3_1 += rA3 * rB1;
               rA0 = pA0[38];
               rB0 = pB0[38];
               rC0_0 += rA0 * rB0;
               rA1 = pA0[104];
               rC1_0 += rA1 * rB0;
               rA2 = pA0[170];
               rC2_0 += rA2 * rB0;
               rA3 = pA0[236];
               rC3_0 += rA3 * rB0;
               rB1 = pB0[104];
               rC0_1 += rA0 * rB1;
               rC1_1 += rA1 * rB1;
               rC2_1 += rA2 * rB1;
               rC3_1 += rA3 * rB1;
               rA0 = pA0[39];
               rB0 = pB0[39];
               rC0_0 += rA0 * rB0;
               rA1 = pA0[105];
               rC1_0 += rA1 * rB0;
               rA2 = pA0[171];
               rC2_0 += rA2 * rB0;
               rA3 = pA0[237];
               rC3_0 += rA3 * rB0;
               rB1 = pB0[105];
               rC0_1 += rA0 * rB1;
               rC1_1 += rA1 * rB1;
               rC2_1 += rA2 * rB1;
               rC3_1 += rA3 * rB1;
               rA0 = pA0[40];
               rB0 = pB0[40];
               rC0_0 += rA0 * rB0;
               rA1 = pA0[106];
               rC1_0 += rA1 * rB0;
               rA2 = pA0[172];
               rC2_0 += rA2 * rB0;
               rA3 = pA0[238];
               rC3_0 += rA3 * rB0;
               rB1 = pB0[106];
               rC0_1 += rA0 * rB1;
               rC1_1 += rA1 * rB1;
               rC2_1 += rA2 * rB1;
               rC3_1 += rA3 * rB1;
               rA0 = pA0[41];
               rB0 = pB0[41];
               rC0_0 += rA0 * rB0;
               rA1 = pA0[107];
               rC1_0 += rA1 * rB0;
               rA2 = pA0[173];
               rC2_0 += rA2 * rB0;
               rA3 = pA0[239];
               rC3_0 += rA3 * rB0;
               rB1 = pB0[107];
               rC0_1 += rA0 * rB1;
               rC1_1 += rA1 * rB1;
               rC2_1 += rA2 * rB1;
               rC3_1 += rA3 * rB1;
               rA0 = pA0[42];
               rB0 = pB0[42];
               rC0_0 += rA0 * rB0;
               rA1 = pA0[108];
               rC1_0 += rA1 * rB0;
               rA2 = pA0[174];
               rC2_0 += rA2 * rB0;
               rA3 = pA0[240];
               rC3_0 += rA3 * rB0;
               rB1 = pB0[108];
               rC0_1 += rA0 * rB1;
               rC1_1 += rA1 * rB1;
               rC2_1 += rA2 * rB1;
               rC3_1 += rA3 * rB1;
               rA0 = pA0[43];
               rB0 = pB0[43];
               rC0_0 += rA0 * rB0;
               rA1 = pA0[109];
               rC1_0 += rA1 * rB0;
               rA2 = pA0[175];
               rC2_0 += rA2 * rB0;
               rA3 = pA0[241];
               rC3_0 += rA3 * rB0;
               rB1 = pB0[109];
               rC0_1 += rA0 * rB1;
               rC1_1 += rA1 * rB1;
               rC2_1 += rA2 * rB1;
               rC3_1 += rA3 * rB1;
               rA0 = pA0[44];
               rB0 = pB0[44];
               rC0_0 += rA0 * rB0;
               rA1 = pA0[110];
               rC1_0 += rA1 * rB0;
               rA2 = pA0[176];
               rC2_0 += rA2 * rB0;
               rA3 = pA0[242];
               rC3_0 += rA3 * rB0;
               rB1 = pB0[110];
               rC0_1 += rA0 * rB1;
               rC1_1 += rA1 * rB1;
               rC2_1 += rA2 * rB1;
               rC3_1 += rA3 * rB1;
               rA0 = pA0[45];
               rB0 = pB0[45];
               rC0_0 += rA0 * rB0;
               rA1 = pA0[111];
               rC1_0 += rA1 * rB0;
               rA2 = pA0[177];
               rC2_0 += rA2 * rB0;
               rA3 = pA0[243];
               rC3_0 += rA3 * rB0;
               rB1 = pB0[111];
               rC0_1 += rA0 * rB1;
               rC1_1 += rA1 * rB1;
               rC2_1 += rA2 * rB1;
               rC3_1 += rA3 * rB1;
               rA0 = pA0[46];
               rB0 = pB0[46];
               rC0_0 += rA0 * rB0;
               rA1 = pA0[112];
               rC1_0 += rA1 * rB0;
               rA2 = pA0[178];
               rC2_0 += rA2 * rB0;
               rA3 = pA0[244];
               rC3_0 += rA3 * rB0;
               rB1 = pB0[112];
               rC0_1 += rA0 * rB1;
               rC1_1 += rA1 * rB1;
               rC2_1 += rA2 * rB1;
               rC3_1 += rA3 * rB1;
               rA0 = pA0[47];
               rB0 = pB0[47];
               rC0_0 += rA0 * rB0;
               rA1 = pA0[113];
               rC1_0 += rA1 * rB0;
               rA2 = pA0[179];
               rC2_0 += rA2 * rB0;
               rA3 = pA0[245];
               rC3_0 += rA3 * rB0;
               rB1 = pB0[113];
               rC0_1 += rA0 * rB1;
               rC1_1 += rA1 * rB1;
               rC2_1 += rA2 * rB1;
               rC3_1 += rA3 * rB1;
               rA0 = pA0[48];
               rB0 = pB0[48];
               rC0_0 += rA0 * rB0;
               rA1 = pA0[114];
               rC1_0 += rA1 * rB0;
               rA2 = pA0[180];
               rC2_0 += rA2 * rB0;
               rA3 = pA0[246];
               rC3_0 += rA3 * rB0;
               rB1 = pB0[114];
               rC0_1 += rA0 * rB1;
               rC1_1 += rA1 * rB1;
               rC2_1 += rA2 * rB1;
               rC3_1 += rA3 * rB1;
               rA0 = pA0[49];
               rB0 = pB0[49];
               rC0_0 += rA0 * rB0;
               rA1 = pA0[115];
               rC1_0 += rA1 * rB0;
               rA2 = pA0[181];
               rC2_0 += rA2 * rB0;
               rA3 = pA0[247];
               rC3_0 += rA3 * rB0;
               rB1 = pB0[115];
               rC0_1 += rA0 * rB1;
               rC1_1 += rA1 * rB1;
               rC2_1 += rA2 * rB1;
               rC3_1 += rA3 * rB1;
               rA0 = pA0[50];
               rB0 = pB0[50];
               rC0_0 += rA0 * rB0;
               rA1 = pA0[116];
               rC1_0 += rA1 * rB0;
               rA2 = pA0[182];
               rC2_0 += rA2 * rB0;
               rA3 = pA0[248];
               rC3_0 += rA3 * rB0;
               rB1 = pB0[116];
               rC0_1 += rA0 * rB1;
               rC1_1 += rA1 * rB1;
               rC2_1 += rA2 * rB1;
               rC3_1 += rA3 * rB1;
               rA0 = pA0[51];
               rB0 = pB0[51];
               rC0_0 += rA0 * rB0;
               rA1 = pA0[117];
               rC1_0 += rA1 * rB0;
               rA2 = pA0[183];
               rC2_0 += rA2 * rB0;
               rA3 = pA0[249];
               rC3_0 += rA3 * rB0;
               rB1 = pB0[117];
               rC0_1 += rA0 * rB1;
               rC1_1 += rA1 * rB1;
               rC2_1 += rA2 * rB1;
               rC3_1 += rA3 * rB1;
               rA0 = pA0[52];
               rB0 = pB0[52];
               rC0_0 += rA0 * rB0;
               rA1 = pA0[118];
               rC1_0 += rA1 * rB0;
               rA2 = pA0[184];
               rC2_0 += rA2 * rB0;
               rA3 = pA0[250];
               rC3_0 += rA3 * rB0;
               rB1 = pB0[118];
               rC0_1 += rA0 * rB1;
               rC1_1 += rA1 * rB1;
               rC2_1 += rA2 * rB1;
               rC3_1 += rA3 * rB1;
               rA0 = pA0[53];
               rB0 = pB0[53];
               rC0_0 += rA0 * rB0;
               rA1 = pA0[119];
               rC1_0 += rA1 * rB0;
               rA2 = pA0[185];
               rC2_0 += rA2 * rB0;
               rA3 = pA0[251];
               rC3_0 += rA3 * rB0;
               rB1 = pB0[119];
               rC0_1 += rA0 * rB1;
               rC1_1 += rA1 * rB1;
               rC2_1 += rA2 * rB1;
               rC3_1 += rA3 * rB1;
               rA0 = pA0[54];
               rB0 = pB0[54];
               rC0_0 += rA0 * rB0;
               rA1 = pA0[120];
               rC1_0 += rA1 * rB0;
               rA2 = pA0[186];
               rC2_0 += rA2 * rB0;
               rA3 = pA0[252];
               rC3_0 += rA3 * rB0;
               rB1 = pB0[120];
               rC0_1 += rA0 * rB1;
               rC1_1 += rA1 * rB1;
               rC2_1 += rA2 * rB1;
               rC3_1 += rA3 * rB1;
               rA0 = pA0[55];
               rB0 = pB0[55];
               rC0_0 += rA0 * rB0;
               rA1 = pA0[121];
               rC1_0 += rA1 * rB0;
               rA2 = pA0[187];
               rC2_0 += rA2 * rB0;
               rA3 = pA0[253];
               rC3_0 += rA3 * rB0;
               rB1 = pB0[121];
               rC0_1 += rA0 * rB1;
               rC1_1 += rA1 * rB1;
               rC2_1 += rA2 * rB1;
               rC3_1 += rA3 * rB1;
               rA0 = pA0[56];
               rB0 = pB0[56];
               rC0_0 += rA0 * rB0;
               rA1 = pA0[122];
               rC1_0 += rA1 * rB0;
               rA2 = pA0[188];
               rC2_0 += rA2 * rB0;
               rA3 = pA0[254];
               rC3_0 += rA3 * rB0;
               rB1 = pB0[122];
               rC0_1 += rA0 * rB1;
               rC1_1 += rA1 * rB1;
               rC2_1 += rA2 * rB1;
               rC3_1 += rA3 * rB1;
               rA0 = pA0[57];
               rB0 = pB0[57];
               rC0_0 += rA0 * rB0;
               rA1 = pA0[123];
               rC1_0 += rA1 * rB0;
               rA2 = pA0[189];
               rC2_0 += rA2 * rB0;
               rA3 = pA0[255];
               rC3_0 += rA3 * rB0;
               rB1 = pB0[123];
               rC0_1 += rA0 * rB1;
               rC1_1 += rA1 * rB1;
               rC2_1 += rA2 * rB1;
               rC3_1 += rA3 * rB1;
               rA0 = pA0[58];
               rB0 = pB0[58];
               rC0_0 += rA0 * rB0;
               rA1 = pA0[124];
               rC1_0 += rA1 * rB0;
               rA2 = pA0[190];
               rC2_0 += rA2 * rB0;
               rA3 = pA0[256];
               rC3_0 += rA3 * rB0;
               rB1 = pB0[124];
               rC0_1 += rA0 * rB1;
               rC1_1 += rA1 * rB1;
               rC2_1 += rA2 * rB1;
               rC3_1 += rA3 * rB1;
               rA0 = pA0[59];
               rB0 = pB0[59];
               rC0_0 += rA0 * rB0;
               rA1 = pA0[125];
               rC1_0 += rA1 * rB0;
               rA2 = pA0[191];
               rC2_0 += rA2 * rB0;
               rA3 = pA0[257];
               rC3_0 += rA3 * rB0;
               rB1 = pB0[125];
               rC0_1 += rA0 * rB1;
               rC1_1 += rA1 * rB1;
               rC2_1 += rA2 * rB1;
               rC3_1 += rA3 * rB1;
               rA0 = pA0[60];
               rB0 = pB0[60];
               rC0_0 += rA0 * rB0;
               rA1 = pA0[126];
               rC1_0 += rA1 * rB0;
               rA2 = pA0[192];
               rC2_0 += rA2 * rB0;
               rA3 = pA0[258];
               rC3_0 += rA3 * rB0;
               rB1 = pB0[126];
               rC0_1 += rA0 * rB1;
               rC1_1 += rA1 * rB1;
               rC2_1 += rA2 * rB1;
               rC3_1 += rA3 * rB1;
               rA0 = pA0[61];
               rB0 = pB0[61];
               rC0_0 += rA0 * rB0;
               rA1 = pA0[127];
               rC1_0 += rA1 * rB0;
               rA2 = pA0[193];
               rC2_0 += rA2 * rB0;
               rA3 = pA0[259];
               rC3_0 += rA3 * rB0;
               rB1 = pB0[127];
               rC0_1 += rA0 * rB1;
               rC1_1 += rA1 * rB1;
               rC2_1 += rA2 * rB1;
               rC3_1 += rA3 * rB1;
               rA0 = pA0[62];
               rB0 = pB0[62];
               rC0_0 += rA0 * rB0;
               rA1 = pA0[128];
               rC1_0 += rA1 * rB0;
               rA2 = pA0[194];
               rC2_0 += rA2 * rB0;
               rA3 = pA0[260];
               rC3_0 += rA3 * rB0;
               rB1 = pB0[128];
               rC0_1 += rA0 * rB1;
               rC1_1 += rA1 * rB1;
               rC2_1 += rA2 * rB1;
               rC3_1 += rA3 * rB1;
               rA0 = pA0[63];
               rB0 = pB0[63];
               rC0_0 += rA0 * rB0;
               rA1 = pA0[129];
               rC1_0 += rA1 * rB0;
               rA2 = pA0[195];
               rC2_0 += rA2 * rB0;
               rA3 = pA0[261];
               rC3_0 += rA3 * rB0;
               rB1 = pB0[129];
               rC0_1 += rA0 * rB1;
               rC1_1 += rA1 * rB1;
               rC2_1 += rA2 * rB1;
               rC3_1 += rA3 * rB1;
               rA0 = pA0[64];
               rB0 = pB0[64];
               rC0_0 += rA0 * rB0;
               rA1 = pA0[130];
               rC1_0 += rA1 * rB0;
               rA2 = pA0[196];
               rC2_0 += rA2 * rB0;
               rA3 = pA0[262];
               rC3_0 += rA3 * rB0;
               rB1 = pB0[130];
               rC0_1 += rA0 * rB1;
               rC1_1 += rA1 * rB1;
               rC2_1 += rA2 * rB1;
               rC3_1 += rA3 * rB1;
               rA0 = pA0[65];
               rB0 = pB0[65];
               rC0_0 += rA0 * rB0;
               rA1 = pA0[131];
               rC1_0 += rA1 * rB0;
               rA2 = pA0[197];
               rC2_0 += rA2 * rB0;
               rA3 = pA0[263];
               rC3_0 += rA3 * rB0;
               rB1 = pB0[131];
               rC0_1 += rA0 * rB1;
               rC1_1 += rA1 * rB1;
               rC2_1 += rA2 * rB1;
               rC3_1 += rA3 * rB1;
               pA0 += incAk;
               pB0 += incBk;
               *pC0 = rC0_0;
               pC0[2] = rC1_0;
               pC0[4] = rC2_0;
               pC0[6] = rC3_0;
               *pC1 = rC0_1;
               pC1[2] = rC1_1;
               pC1[4] = rC2_1;
               pC1[6] = rC3_1;
               pC0 += incCm;
               pC1 += incCm;
               pA0 += incAm;
               pB0 += incBm;
            }
            while(pA0 != stM);
            pC0 += incCn;
            pC1 += incCn;
            pA0 += incAn;
            pB0 += incBn;
         }
         while(pB0 != stN);
      }
   }
   if (k=N-Nb)
      ATL_cJIK0x0x66TN4x1x66_a1_bX(M, k, 66, alpha, ca, lda, cb + (((Nb) << 6)+((Nb) << 1)), ldb, beta, cc + (((Nb*ldc) << 1)), ldc);
   if (Nb && (k=M-Mb))
      ATL_cJIK0x0x66TN1x2x66_a1_bX(k, Nb, 66, alpha, ca + (((Mb) << 6)+((Mb) << 1)), lda, cb, ldb, beta, cc + (((Mb) << 1)), ldc);
}
#ifdef incAm
   #undef incAm
#endif
#ifdef incAn
   #undef incAn
#endif
#ifdef incAk
   #undef incAk
#endif
#ifdef incBm
   #undef incBm
#endif
#ifdef incBn
   #undef incBn
#endif
#ifdef incBk
   #undef incBk
#endif
#ifdef incCm
   #undef incCm
#endif
#ifdef incCn
   #undef incCn
#endif
#ifdef incCk
   #undef incCk
#endif
#ifdef Mb
   #undef Mb
#endif
#ifdef Nb
   #undef Nb
#endif
#ifdef Kb
   #undef Kb
#endif
