#ifndef ATL_RESTRICT
#if defined(__STDC_VERSION__) && (__STDC_VERSION__/100 >= 1999)
   #define ATL_RESTRICT restrict
#else
   #define ATL_RESTRICT
#endif
#endif
#ifndef ATL_RESTRICT
#if defined(__STDC_VERSION__) && (__STDC_VERSION__/100 >= 1999)
   #define ATL_RESTRICT restrict
#else
   #define ATL_RESTRICT
#endif
#endif
#ifndef ATL_RESTRICT
#if defined(__STDC_VERSION__) && (__STDC_VERSION__/100 >= 1999)
   #define ATL_RESTRICT restrict
#else
   #define ATL_RESTRICT
#endif
#endif
static void ATL_cJIK0x0x13TN1x1x13_a1_bX
   (const int M, const int N, const int K, const float alpha, const float * ATL_RESTRICT A, const int lda, const float * ATL_RESTRICT B, const int ldb, const float beta, float * ATL_RESTRICT C, const int ldc)
/*
 * matmul with TA=T, TB=N, MB=0, NB=0, KB=13, 
 * lda=13, ldb=13, ldc=0, mu=1, nu=1, ku=13, pf=0
 * Generated by ATLAS/tune/blas/gemm/emit_mm.c (3.9.23)
 */
{
   #define Mb M
   #define Nb N
   const float *stM = A + (13*(Mb));
   const float *stN = B + (13*(Nb));
   #define incAk 13
   const int incAm = 0, incAn = -(13*(Mb));
   #define incBk 13
   const int incBm = -13, incBn = 13;
   #define incCm 2
   const int incCn = (((ldc) << 1)) - (((Mb) << 1));
   float *pC0=C;
   const float *pA0=A;
   const float *pB0=B;
   register int k;
   register float rA0;
   register float rB0;
   register float rC0_0;
   do /* N-loop */
   {
      do /* M-loop */
      {
         rA0 = beta;
         rC0_0 = *pC0;
         rC0_0 *= rA0;
         rA0 = *pA0;
         rB0 = *pB0;
         rC0_0 += rA0 * rB0;
         rA0 = pA0[1];
         rB0 = pB0[1];
         rC0_0 += rA0 * rB0;
         rA0 = pA0[2];
         rB0 = pB0[2];
         rC0_0 += rA0 * rB0;
         rA0 = pA0[3];
         rB0 = pB0[3];
         rC0_0 += rA0 * rB0;
         rA0 = pA0[4];
         rB0 = pB0[4];
         rC0_0 += rA0 * rB0;
         rA0 = pA0[5];
         rB0 = pB0[5];
         rC0_0 += rA0 * rB0;
         rA0 = pA0[6];
         rB0 = pB0[6];
         rC0_0 += rA0 * rB0;
         rA0 = pA0[7];
         rB0 = pB0[7];
         rC0_0 += rA0 * rB0;
         rA0 = pA0[8];
         rB0 = pB0[8];
         rC0_0 += rA0 * rB0;
         rA0 = pA0[9];
         rB0 = pB0[9];
         rC0_0 += rA0 * rB0;
         rA0 = pA0[10];
         rB0 = pB0[10];
         rC0_0 += rA0 * rB0;
         rA0 = pA0[11];
         rB0 = pB0[11];
         rC0_0 += rA0 * rB0;
         rA0 = pA0[12];
         rB0 = pB0[12];
         rC0_0 += rA0 * rB0;
         pA0 += incAk;
         pB0 += incBk;
         *pC0 = rC0_0;
         pC0 += incCm;
         pA0 += incAm;
         pB0 += incBm;
      }
      while(pA0 != stM);
      pC0 += incCn;
      pA0 += incAn;
      pB0 += incBn;
   }
   while(pB0 != stN);
}
#ifdef incAm
   #undef incAm
#endif
#ifdef incAn
   #undef incAn
#endif
#ifdef incAk
   #undef incAk
#endif
#ifdef incBm
   #undef incBm
#endif
#ifdef incBn
   #undef incBn
#endif
#ifdef incBk
   #undef incBk
#endif
#ifdef incCm
   #undef incCm
#endif
#ifdef incCn
   #undef incCn
#endif
#ifdef incCk
   #undef incCk
#endif
#ifdef Mb
   #undef Mb
#endif
#ifdef Nb
   #undef Nb
#endif
#ifdef Kb
   #undef Kb
#endif
static void ATL_cJIK0x0x13TN4x1x13_a1_bX
   (const int M, const int N, const int K, const float alpha, const float * ATL_RESTRICT A, const int lda, const float * ATL_RESTRICT B, const int ldb, const float beta, float * ATL_RESTRICT C, const int ldc)
/*
 * matmul with TA=T, TB=N, MB=0, NB=0, KB=13, 
 * lda=13, ldb=13, ldc=0, mu=4, nu=1, ku=13, pf=0
 * Generated by ATLAS/tune/blas/gemm/emit_mm.c (3.9.23)
 */
{
   const int Mb = (M>>2)<<2;
   #define Nb N
   const float *ca=A, *cb=B;
   float *cc=C;
   const float *stM = A + (13*(Mb));
   const float *stN = B + (13*(Nb));
   #define incAk 13
   const int incAm = 39, incAn = -(13*(Mb));
   #define incBk 13
   const int incBm = -13, incBn = 13;
   #define incCm 8
   const int incCn = (((ldc) << 1)) - (((Mb) << 1));
   float *pC0=C;
   const float *pA0=A;
   const float *pB0=B;
   register int k;
   register float rA0, rA1, rA2, rA3;
   register float rB0;
   register float rC0_0, rC1_0, rC2_0, rC3_0;
   if (pA0 != stM)
   {
      do /* N-loop */
      {
         do /* M-loop */
         {
            rA0 = beta;
            rC0_0 = *pC0;
            rC0_0 *= rA0;
            rC1_0 = pC0[2];
            rC1_0 *= rA0;
            rC2_0 = pC0[4];
            rC2_0 *= rA0;
            rC3_0 = pC0[6];
            rC3_0 *= rA0;
            rA0 = *pA0;
            rB0 = *pB0;
            rC0_0 += rA0 * rB0;
            rA1 = pA0[13];
            rC1_0 += rA1 * rB0;
            rA2 = pA0[26];
            rC2_0 += rA2 * rB0;
            rA3 = pA0[39];
            rC3_0 += rA3 * rB0;
            rA0 = pA0[1];
            rB0 = pB0[1];
            rC0_0 += rA0 * rB0;
            rA1 = pA0[14];
            rC1_0 += rA1 * rB0;
            rA2 = pA0[27];
            rC2_0 += rA2 * rB0;
            rA3 = pA0[40];
            rC3_0 += rA3 * rB0;
            rA0 = pA0[2];
            rB0 = pB0[2];
            rC0_0 += rA0 * rB0;
            rA1 = pA0[15];
            rC1_0 += rA1 * rB0;
            rA2 = pA0[28];
            rC2_0 += rA2 * rB0;
            rA3 = pA0[41];
            rC3_0 += rA3 * rB0;
            rA0 = pA0[3];
            rB0 = pB0[3];
            rC0_0 += rA0 * rB0;
            rA1 = pA0[16];
            rC1_0 += rA1 * rB0;
            rA2 = pA0[29];
            rC2_0 += rA2 * rB0;
            rA3 = pA0[42];
            rC3_0 += rA3 * rB0;
            rA0 = pA0[4];
            rB0 = pB0[4];
            rC0_0 += rA0 * rB0;
            rA1 = pA0[17];
            rC1_0 += rA1 * rB0;
            rA2 = pA0[30];
            rC2_0 += rA2 * rB0;
            rA3 = pA0[43];
            rC3_0 += rA3 * rB0;
            rA0 = pA0[5];
            rB0 = pB0[5];
            rC0_0 += rA0 * rB0;
            rA1 = pA0[18];
            rC1_0 += rA1 * rB0;
            rA2 = pA0[31];
            rC2_0 += rA2 * rB0;
            rA3 = pA0[44];
            rC3_0 += rA3 * rB0;
            rA0 = pA0[6];
            rB0 = pB0[6];
            rC0_0 += rA0 * rB0;
            rA1 = pA0[19];
            rC1_0 += rA1 * rB0;
            rA2 = pA0[32];
            rC2_0 += rA2 * rB0;
            rA3 = pA0[45];
            rC3_0 += rA3 * rB0;
            rA0 = pA0[7];
            rB0 = pB0[7];
            rC0_0 += rA0 * rB0;
            rA1 = pA0[20];
            rC1_0 += rA1 * rB0;
            rA2 = pA0[33];
            rC2_0 += rA2 * rB0;
            rA3 = pA0[46];
            rC3_0 += rA3 * rB0;
            rA0 = pA0[8];
            rB0 = pB0[8];
            rC0_0 += rA0 * rB0;
            rA1 = pA0[21];
            rC1_0 += rA1 * rB0;
            rA2 = pA0[34];
            rC2_0 += rA2 * rB0;
            rA3 = pA0[47];
            rC3_0 += rA3 * rB0;
            rA0 = pA0[9];
            rB0 = pB0[9];
            rC0_0 += rA0 * rB0;
            rA1 = pA0[22];
            rC1_0 += rA1 * rB0;
            rA2 = pA0[35];
            rC2_0 += rA2 * rB0;
            rA3 = pA0[48];
            rC3_0 += rA3 * rB0;
            rA0 = pA0[10];
            rB0 = pB0[10];
            rC0_0 += rA0 * rB0;
            rA1 = pA0[23];
            rC1_0 += rA1 * rB0;
            rA2 = pA0[36];
            rC2_0 += rA2 * rB0;
            rA3 = pA0[49];
            rC3_0 += rA3 * rB0;
            rA0 = pA0[11];
            rB0 = pB0[11];
            rC0_0 += rA0 * rB0;
            rA1 = pA0[24];
            rC1_0 += rA1 * rB0;
            rA2 = pA0[37];
            rC2_0 += rA2 * rB0;
            rA3 = pA0[50];
            rC3_0 += rA3 * rB0;
            rA0 = pA0[12];
            rB0 = pB0[12];
            rC0_0 += rA0 * rB0;
            rA1 = pA0[25];
            rC1_0 += rA1 * rB0;
            rA2 = pA0[38];
            rC2_0 += rA2 * rB0;
            rA3 = pA0[51];
            rC3_0 += rA3 * rB0;
            pA0 += incAk;
            pB0 += incBk;
            *pC0 = rC0_0;
            pC0[2] = rC1_0;
            pC0[4] = rC2_0;
            pC0[6] = rC3_0;
            pC0 += incCm;
            pA0 += incAm;
            pB0 += incBm;
         }
         while(pA0 != stM);
         pC0 += incCn;
         pA0 += incAn;
         pB0 += incBn;
      }
      while(pB0 != stN);
   }
   if (k=M-Mb)
      ATL_cJIK0x0x13TN1x1x13_a1_bX(k, N, 13, alpha, ca + (13*(Mb)), lda, cb, ldb, beta, cc + (((Mb) << 1)), ldc);
}
#ifdef incAm
   #undef incAm
#endif
#ifdef incAn
   #undef incAn
#endif
#ifdef incAk
   #undef incAk
#endif
#ifdef incBm
   #undef incBm
#endif
#ifdef incBn
   #undef incBn
#endif
#ifdef incBk
   #undef incBk
#endif
#ifdef incCm
   #undef incCm
#endif
#ifdef incCn
   #undef incCn
#endif
#ifdef incCk
   #undef incCk
#endif
#ifdef Mb
   #undef Mb
#endif
#ifdef Nb
   #undef Nb
#endif
#ifdef Kb
   #undef Kb
#endif
#ifndef ATL_RESTRICT
#if defined(__STDC_VERSION__) && (__STDC_VERSION__/100 >= 1999)
   #define ATL_RESTRICT restrict
#else
   #define ATL_RESTRICT
#endif
#endif
static void ATL_cJIK0x0x13TN1x2x13_a1_bX
   (const int M, const int N, const int K, const float alpha, const float * ATL_RESTRICT A, const int lda, const float * ATL_RESTRICT B, const int ldb, const float beta, float * ATL_RESTRICT C, const int ldc)
/*
 * matmul with TA=T, TB=N, MB=0, NB=0, KB=13, 
 * lda=13, ldb=13, ldc=0, mu=1, nu=2, ku=13, pf=0
 * Generated by ATLAS/tune/blas/gemm/emit_mm.c (3.9.23)
 */
{
   #define Mb M
   const int Nb = (N>>1)<<1;
   const float *ca=A, *cb=B;
   float *cc=C;
   const float *stM = A + (13*(Mb));
   const float *stN = B + (13*(Nb));
   #define incAk 13
   const int incAm = 0, incAn = -(13*(Mb));
   #define incBk 13
   const int incBm = -13, incBn = 26;
   #define incCm 2
   const int incCn = (((ldc) << 2)) - (((Mb) << 1));
   float *pC0=C, *pC1=pC0+(((ldc) << 1));
   const float *pA0=A;
   const float *pB0=B;
   register int k;
   register float rA0;
   register float rB0, rB1;
   register float rC0_0, rC0_1;
   if (pB0 != stN)
   {
      do /* N-loop */
      {
         do /* M-loop */
         {
            rA0 = beta;
            rC0_0 = *pC0;
            rC0_0 *= rA0;
            rC0_1 = *pC1;
            rC0_1 *= rA0;
            rA0 = *pA0;
            rB0 = *pB0;
            rC0_0 += rA0 * rB0;
            rB1 = pB0[13];
            rC0_1 += rA0 * rB1;
            rA0 = pA0[1];
            rB0 = pB0[1];
            rC0_0 += rA0 * rB0;
            rB1 = pB0[14];
            rC0_1 += rA0 * rB1;
            rA0 = pA0[2];
            rB0 = pB0[2];
            rC0_0 += rA0 * rB0;
            rB1 = pB0[15];
            rC0_1 += rA0 * rB1;
            rA0 = pA0[3];
            rB0 = pB0[3];
            rC0_0 += rA0 * rB0;
            rB1 = pB0[16];
            rC0_1 += rA0 * rB1;
            rA0 = pA0[4];
            rB0 = pB0[4];
            rC0_0 += rA0 * rB0;
            rB1 = pB0[17];
            rC0_1 += rA0 * rB1;
            rA0 = pA0[5];
            rB0 = pB0[5];
            rC0_0 += rA0 * rB0;
            rB1 = pB0[18];
            rC0_1 += rA0 * rB1;
            rA0 = pA0[6];
            rB0 = pB0[6];
            rC0_0 += rA0 * rB0;
            rB1 = pB0[19];
            rC0_1 += rA0 * rB1;
            rA0 = pA0[7];
            rB0 = pB0[7];
            rC0_0 += rA0 * rB0;
            rB1 = pB0[20];
            rC0_1 += rA0 * rB1;
            rA0 = pA0[8];
            rB0 = pB0[8];
            rC0_0 += rA0 * rB0;
            rB1 = pB0[21];
            rC0_1 += rA0 * rB1;
            rA0 = pA0[9];
            rB0 = pB0[9];
            rC0_0 += rA0 * rB0;
            rB1 = pB0[22];
            rC0_1 += rA0 * rB1;
            rA0 = pA0[10];
            rB0 = pB0[10];
            rC0_0 += rA0 * rB0;
            rB1 = pB0[23];
            rC0_1 += rA0 * rB1;
            rA0 = pA0[11];
            rB0 = pB0[11];
            rC0_0 += rA0 * rB0;
            rB1 = pB0[24];
            rC0_1 += rA0 * rB1;
            rA0 = pA0[12];
            rB0 = pB0[12];
            rC0_0 += rA0 * rB0;
            rB1 = pB0[25];
            rC0_1 += rA0 * rB1;
            pA0 += incAk;
            pB0 += incBk;
            *pC0 = rC0_0;
            *pC1 = rC0_1;
            pC0 += incCm;
            pC1 += incCm;
            pA0 += incAm;
            pB0 += incBm;
         }
         while(pA0 != stM);
         pC0 += incCn;
         pC1 += incCn;
         pA0 += incAn;
         pB0 += incBn;
      }
      while(pB0 != stN);
   }
   if (k=N-Nb)
      ATL_cJIK0x0x13TN1x1x13_a1_bX(M, k, 13, alpha, ca, lda, cb + (13*(Nb)), ldb, beta, cc + (((Nb*ldc) << 1)), ldc);
}
#ifdef incAm
   #undef incAm
#endif
#ifdef incAn
   #undef incAn
#endif
#ifdef incAk
   #undef incAk
#endif
#ifdef incBm
   #undef incBm
#endif
#ifdef incBn
   #undef incBn
#endif
#ifdef incBk
   #undef incBk
#endif
#ifdef incCm
   #undef incCm
#endif
#ifdef incCn
   #undef incCn
#endif
#ifdef incCk
   #undef incCk
#endif
#ifdef Mb
   #undef Mb
#endif
#ifdef Nb
   #undef Nb
#endif
#ifdef Kb
   #undef Kb
#endif
void ATL_cJIK0x0x13TN13x13x0_a1_bX
   (const int M, const int N, const int K, const float alpha, const float * ATL_RESTRICT A, const int lda, const float * ATL_RESTRICT B, const int ldb, const float beta, float * ATL_RESTRICT C, const int ldc)
/*
 * matmul with TA=T, TB=N, MB=0, NB=0, KB=13, 
 * lda=13, ldb=13, ldc=0, mu=4, nu=2, ku=13, pf=0
 * Generated by ATLAS/tune/blas/gemm/emit_mm.c (3.9.23)
 */
{
   const int Mb = (M>>2)<<2;
   const int Nb = (N>>1)<<1;
   const float *ca=A, *cb=B;
   float *cc=C;
   const float *stM = A + (13*(Mb));
   const float *stN = B + (13*(Nb));
   #define incAk 13
   const int incAm = 39, incAn = -(13*(Mb));
   #define incBk 13
   const int incBm = -13, incBn = 26;
   #define incCm 8
   const int incCn = (((ldc) << 2)) - (((Mb) << 1));
   float *pC0=C, *pC1=pC0+(((ldc) << 1));
   const float *pA0=A;
   const float *pB0=B;
   register int k;
   register float rA0, rA1, rA2, rA3;
   register float rB0, rB1;
   register float rC0_0, rC1_0, rC2_0, rC3_0, rC0_1, rC1_1, rC2_1, rC3_1;
   if (pA0 != stM)
   {
      if (pB0 != stN)
      {
         do /* N-loop */
         {
            do /* M-loop */
            {
               rA0 = beta;
               rC0_0 = *pC0;
               rC0_0 *= rA0;
               rC1_0 = pC0[2];
               rC1_0 *= rA0;
               rC2_0 = pC0[4];
               rC2_0 *= rA0;
               rC3_0 = pC0[6];
               rC3_0 *= rA0;
               rC0_1 = *pC1;
               rC0_1 *= rA0;
               rC1_1 = pC1[2];
               rC1_1 *= rA0;
               rC2_1 = pC1[4];
               rC2_1 *= rA0;
               rC3_1 = pC1[6];
               rC3_1 *= rA0;
               rA0 = *pA0;
               rB0 = *pB0;
               rC0_0 += rA0 * rB0;
               rA1 = pA0[13];
               rC1_0 += rA1 * rB0;
               rA2 = pA0[26];
               rC2_0 += rA2 * rB0;
               rA3 = pA0[39];
               rC3_0 += rA3 * rB0;
               rB1 = pB0[13];
               rC0_1 += rA0 * rB1;
               rC1_1 += rA1 * rB1;
               rC2_1 += rA2 * rB1;
               rC3_1 += rA3 * rB1;
               rA0 = pA0[1];
               rB0 = pB0[1];
               rC0_0 += rA0 * rB0;
               rA1 = pA0[14];
               rC1_0 += rA1 * rB0;
               rA2 = pA0[27];
               rC2_0 += rA2 * rB0;
               rA3 = pA0[40];
               rC3_0 += rA3 * rB0;
               rB1 = pB0[14];
               rC0_1 += rA0 * rB1;
               rC1_1 += rA1 * rB1;
               rC2_1 += rA2 * rB1;
               rC3_1 += rA3 * rB1;
               rA0 = pA0[2];
               rB0 = pB0[2];
               rC0_0 += rA0 * rB0;
               rA1 = pA0[15];
               rC1_0 += rA1 * rB0;
               rA2 = pA0[28];
               rC2_0 += rA2 * rB0;
               rA3 = pA0[41];
               rC3_0 += rA3 * rB0;
               rB1 = pB0[15];
               rC0_1 += rA0 * rB1;
               rC1_1 += rA1 * rB1;
               rC2_1 += rA2 * rB1;
               rC3_1 += rA3 * rB1;
               rA0 = pA0[3];
               rB0 = pB0[3];
               rC0_0 += rA0 * rB0;
               rA1 = pA0[16];
               rC1_0 += rA1 * rB0;
               rA2 = pA0[29];
               rC2_0 += rA2 * rB0;
               rA3 = pA0[42];
               rC3_0 += rA3 * rB0;
               rB1 = pB0[16];
               rC0_1 += rA0 * rB1;
               rC1_1 += rA1 * rB1;
               rC2_1 += rA2 * rB1;
               rC3_1 += rA3 * rB1;
               rA0 = pA0[4];
               rB0 = pB0[4];
               rC0_0 += rA0 * rB0;
               rA1 = pA0[17];
               rC1_0 += rA1 * rB0;
               rA2 = pA0[30];
               rC2_0 += rA2 * rB0;
               rA3 = pA0[43];
               rC3_0 += rA3 * rB0;
               rB1 = pB0[17];
               rC0_1 += rA0 * rB1;
               rC1_1 += rA1 * rB1;
               rC2_1 += rA2 * rB1;
               rC3_1 += rA3 * rB1;
               rA0 = pA0[5];
               rB0 = pB0[5];
               rC0_0 += rA0 * rB0;
               rA1 = pA0[18];
               rC1_0 += rA1 * rB0;
               rA2 = pA0[31];
               rC2_0 += rA2 * rB0;
               rA3 = pA0[44];
               rC3_0 += rA3 * rB0;
               rB1 = pB0[18];
               rC0_1 += rA0 * rB1;
               rC1_1 += rA1 * rB1;
               rC2_1 += rA2 * rB1;
               rC3_1 += rA3 * rB1;
               rA0 = pA0[6];
               rB0 = pB0[6];
               rC0_0 += rA0 * rB0;
               rA1 = pA0[19];
               rC1_0 += rA1 * rB0;
               rA2 = pA0[32];
               rC2_0 += rA2 * rB0;
               rA3 = pA0[45];
               rC3_0 += rA3 * rB0;
               rB1 = pB0[19];
               rC0_1 += rA0 * rB1;
               rC1_1 += rA1 * rB1;
               rC2_1 += rA2 * rB1;
               rC3_1 += rA3 * rB1;
               rA0 = pA0[7];
               rB0 = pB0[7];
               rC0_0 += rA0 * rB0;
               rA1 = pA0[20];
               rC1_0 += rA1 * rB0;
               rA2 = pA0[33];
               rC2_0 += rA2 * rB0;
               rA3 = pA0[46];
               rC3_0 += rA3 * rB0;
               rB1 = pB0[20];
               rC0_1 += rA0 * rB1;
               rC1_1 += rA1 * rB1;
               rC2_1 += rA2 * rB1;
               rC3_1 += rA3 * rB1;
               rA0 = pA0[8];
               rB0 = pB0[8];
               rC0_0 += rA0 * rB0;
               rA1 = pA0[21];
               rC1_0 += rA1 * rB0;
               rA2 = pA0[34];
               rC2_0 += rA2 * rB0;
               rA3 = pA0[47];
               rC3_0 += rA3 * rB0;
               rB1 = pB0[21];
               rC0_1 += rA0 * rB1;
               rC1_1 += rA1 * rB1;
               rC2_1 += rA2 * rB1;
               rC3_1 += rA3 * rB1;
               rA0 = pA0[9];
               rB0 = pB0[9];
               rC0_0 += rA0 * rB0;
               rA1 = pA0[22];
               rC1_0 += rA1 * rB0;
               rA2 = pA0[35];
               rC2_0 += rA2 * rB0;
               rA3 = pA0[48];
               rC3_0 += rA3 * rB0;
               rB1 = pB0[22];
               rC0_1 += rA0 * rB1;
               rC1_1 += rA1 * rB1;
               rC2_1 += rA2 * rB1;
               rC3_1 += rA3 * rB1;
               rA0 = pA0[10];
               rB0 = pB0[10];
               rC0_0 += rA0 * rB0;
               rA1 = pA0[23];
               rC1_0 += rA1 * rB0;
               rA2 = pA0[36];
               rC2_0 += rA2 * rB0;
               rA3 = pA0[49];
               rC3_0 += rA3 * rB0;
               rB1 = pB0[23];
               rC0_1 += rA0 * rB1;
               rC1_1 += rA1 * rB1;
               rC2_1 += rA2 * rB1;
               rC3_1 += rA3 * rB1;
               rA0 = pA0[11];
               rB0 = pB0[11];
               rC0_0 += rA0 * rB0;
               rA1 = pA0[24];
               rC1_0 += rA1 * rB0;
               rA2 = pA0[37];
               rC2_0 += rA2 * rB0;
               rA3 = pA0[50];
               rC3_0 += rA3 * rB0;
               rB1 = pB0[24];
               rC0_1 += rA0 * rB1;
               rC1_1 += rA1 * rB1;
               rC2_1 += rA2 * rB1;
               rC3_1 += rA3 * rB1;
               rA0 = pA0[12];
               rB0 = pB0[12];
               rC0_0 += rA0 * rB0;
               rA1 = pA0[25];
               rC1_0 += rA1 * rB0;
               rA2 = pA0[38];
               rC2_0 += rA2 * rB0;
               rA3 = pA0[51];
               rC3_0 += rA3 * rB0;
               rB1 = pB0[25];
               rC0_1 += rA0 * rB1;
               rC1_1 += rA1 * rB1;
               rC2_1 += rA2 * rB1;
               rC3_1 += rA3 * rB1;
               pA0 += incAk;
               pB0 += incBk;
               *pC0 = rC0_0;
               pC0[2] = rC1_0;
               pC0[4] = rC2_0;
               pC0[6] = rC3_0;
               *pC1 = rC0_1;
               pC1[2] = rC1_1;
               pC1[4] = rC2_1;
               pC1[6] = rC3_1;
               pC0 += incCm;
               pC1 += incCm;
               pA0 += incAm;
               pB0 += incBm;
            }
            while(pA0 != stM);
            pC0 += incCn;
            pC1 += incCn;
            pA0 += incAn;
            pB0 += incBn;
         }
         while(pB0 != stN);
      }
   }
   if (k=N-Nb)
      ATL_cJIK0x0x13TN4x1x13_a1_bX(M, k, 13, alpha, ca, lda, cb + (13*(Nb)), ldb, beta, cc + (((Nb*ldc) << 1)), ldc);
   if (Nb && (k=M-Mb))
      ATL_cJIK0x0x13TN1x2x13_a1_bX(k, Nb, 13, alpha, ca + (13*(Mb)), lda, cb, ldb, beta, cc + (((Mb) << 1)), ldc);
}
#ifdef incAm
   #undef incAm
#endif
#ifdef incAn
   #undef incAn
#endif
#ifdef incAk
   #undef incAk
#endif
#ifdef incBm
   #undef incBm
#endif
#ifdef incBn
   #undef incBn
#endif
#ifdef incBk
   #undef incBk
#endif
#ifdef incCm
   #undef incCm
#endif
#ifdef incCn
   #undef incCn
#endif
#ifdef incCk
   #undef incCk
#endif
#ifdef Mb
   #undef Mb
#endif
#ifdef Nb
   #undef Nb
#endif
#ifdef Kb
   #undef Kb
#endif
