#ifndef ATL_RESTRICT
#if defined(__STDC_VERSION__) && (__STDC_VERSION__/100 >= 1999)
   #define ATL_RESTRICT restrict
#else
   #define ATL_RESTRICT
#endif
#endif
#ifndef ATL_RESTRICT
#if defined(__STDC_VERSION__) && (__STDC_VERSION__/100 >= 1999)
   #define ATL_RESTRICT restrict
#else
   #define ATL_RESTRICT
#endif
#endif
#ifndef ATL_RESTRICT
#if defined(__STDC_VERSION__) && (__STDC_VERSION__/100 >= 1999)
   #define ATL_RESTRICT restrict
#else
   #define ATL_RESTRICT
#endif
#endif
static void ATL_dJIK0x0x48TN1x1x24_aX_bX
   (const int M, const int N, const int K, const double alpha, const double * ATL_RESTRICT A, const int lda, const double * ATL_RESTRICT B, const int ldb, const double beta, double * ATL_RESTRICT C, const int ldc)
/*
 * matmul with TA=T, TB=N, MB=0, NB=0, KB=48, 
 * lda=0, ldb=0, ldc=0, mu=1, nu=1, ku=24, pf=0
 * Generated by ATLAS/tune/blas/gemm/emit_mm.c (3.9.23)
 */
{
   #define Mb M
   #define Nb N
   const double *stM = A + (lda*Mb);
   const double *stN = B + (ldb*Nb);
   const double BetaAlpha = beta / alpha;
   #define incAk 24
   const int incAm = ((lda) - 48), incAn = -(Mb*lda);
   #define incBk 24
   const int incBm = -48, incBn = (ldb);
   const int incAk0 = ((incAk) / 24), incBk0 = ((incBk) / 24);
   #define incCm 1
   const int incCn = (ldc) - (Mb);
   double *pC0=C;
   const double *pA0=A;
   const double *pB0=B;
   register int k;
   register double rA0;
   register double rB0;
   register double m0;
   register double rC0_0;
   do /* N-loop */
   {
      do /* M-loop */
      {
         rA0 = BetaAlpha;
         rC0_0 = *pC0;
         rC0_0 *= rA0;
/*
 *       Start pipeline
 */
         rA0 = *pA0;
         rB0 = *pB0;
         m0 = rA0 * rB0;
         rA0 = pA0[1];
         rB0 = pB0[1];

         pA0 += (incAk0);
         pB0 += (incBk0);
         for (k=0; k < 24; k += 24) /* easy loop to unroll */
         {
            rC0_0 += m0;
            m0 = rA0 * rB0;
            rA0 = pA0[1];
            rB0 = pB0[1];
            rC0_0 += m0;
            m0 = rA0 * rB0;
            rA0 = pA0[2];
            rB0 = pB0[2];
            rC0_0 += m0;
            m0 = rA0 * rB0;
            rA0 = pA0[3];
            rB0 = pB0[3];
            rC0_0 += m0;
            m0 = rA0 * rB0;
            rA0 = pA0[4];
            rB0 = pB0[4];
            rC0_0 += m0;
            m0 = rA0 * rB0;
            rA0 = pA0[5];
            rB0 = pB0[5];
            rC0_0 += m0;
            m0 = rA0 * rB0;
            rA0 = pA0[6];
            rB0 = pB0[6];
            rC0_0 += m0;
            m0 = rA0 * rB0;
            rA0 = pA0[7];
            rB0 = pB0[7];
            rC0_0 += m0;
            m0 = rA0 * rB0;
            rA0 = pA0[8];
            rB0 = pB0[8];
            rC0_0 += m0;
            m0 = rA0 * rB0;
            rA0 = pA0[9];
            rB0 = pB0[9];
            rC0_0 += m0;
            m0 = rA0 * rB0;
            rA0 = pA0[10];
            rB0 = pB0[10];
            rC0_0 += m0;
            m0 = rA0 * rB0;
            rA0 = pA0[11];
            rB0 = pB0[11];
            rC0_0 += m0;
            m0 = rA0 * rB0;
            rA0 = pA0[12];
            rB0 = pB0[12];
            rC0_0 += m0;
            m0 = rA0 * rB0;
            rA0 = pA0[13];
            rB0 = pB0[13];
            rC0_0 += m0;
            m0 = rA0 * rB0;
            rA0 = pA0[14];
            rB0 = pB0[14];
            rC0_0 += m0;
            m0 = rA0 * rB0;
            rA0 = pA0[15];
            rB0 = pB0[15];
            rC0_0 += m0;
            m0 = rA0 * rB0;
            rA0 = pA0[16];
            rB0 = pB0[16];
            rC0_0 += m0;
            m0 = rA0 * rB0;
            rA0 = pA0[17];
            rB0 = pB0[17];
            rC0_0 += m0;
            m0 = rA0 * rB0;
            rA0 = pA0[18];
            rB0 = pB0[18];
            rC0_0 += m0;
            m0 = rA0 * rB0;
            rA0 = pA0[19];
            rB0 = pB0[19];
            rC0_0 += m0;
            m0 = rA0 * rB0;
            rA0 = pA0[20];
            rB0 = pB0[20];
            rC0_0 += m0;
            m0 = rA0 * rB0;
            rA0 = pA0[21];
            rB0 = pB0[21];
            rC0_0 += m0;
            m0 = rA0 * rB0;
            rA0 = pA0[22];
            rB0 = pB0[22];
            rC0_0 += m0;
            m0 = rA0 * rB0;
            rA0 = pA0[23];
            rB0 = pB0[23];
            rC0_0 += m0;
            m0 = rA0 * rB0;
            rA0 = pA0[24];
            rB0 = pB0[24];
            pA0 += incAk;
            pB0 += incBk;
         } /* end K-loop */
         rC0_0 += m0;
         m0 = rA0 * rB0;
         rA0 = pA0[1];
         rB0 = pB0[1];
         rC0_0 += m0;
         m0 = rA0 * rB0;
         rA0 = pA0[2];
         rB0 = pB0[2];
         rC0_0 += m0;
         m0 = rA0 * rB0;
         rA0 = pA0[3];
         rB0 = pB0[3];
         rC0_0 += m0;
         m0 = rA0 * rB0;
         rA0 = pA0[4];
         rB0 = pB0[4];
         rC0_0 += m0;
         m0 = rA0 * rB0;
         rA0 = pA0[5];
         rB0 = pB0[5];
         rC0_0 += m0;
         m0 = rA0 * rB0;
         rA0 = pA0[6];
         rB0 = pB0[6];
         rC0_0 += m0;
         m0 = rA0 * rB0;
         rA0 = pA0[7];
         rB0 = pB0[7];
         rC0_0 += m0;
         m0 = rA0 * rB0;
         rA0 = pA0[8];
         rB0 = pB0[8];
         rC0_0 += m0;
         m0 = rA0 * rB0;
         rA0 = pA0[9];
         rB0 = pB0[9];
         rC0_0 += m0;
         m0 = rA0 * rB0;
         rA0 = pA0[10];
         rB0 = pB0[10];
         rC0_0 += m0;
         m0 = rA0 * rB0;
         rA0 = pA0[11];
         rB0 = pB0[11];
         rC0_0 += m0;
         m0 = rA0 * rB0;
         rA0 = pA0[12];
         rB0 = pB0[12];
         rC0_0 += m0;
         m0 = rA0 * rB0;
         rA0 = pA0[13];
         rB0 = pB0[13];
         rC0_0 += m0;
         m0 = rA0 * rB0;
         rA0 = pA0[14];
         rB0 = pB0[14];
         rC0_0 += m0;
         m0 = rA0 * rB0;
         rA0 = pA0[15];
         rB0 = pB0[15];
         rC0_0 += m0;
         m0 = rA0 * rB0;
         rA0 = pA0[16];
         rB0 = pB0[16];
         rC0_0 += m0;
         m0 = rA0 * rB0;
         rA0 = pA0[17];
         rB0 = pB0[17];
         rC0_0 += m0;
         m0 = rA0 * rB0;
         rA0 = pA0[18];
         rB0 = pB0[18];
         rC0_0 += m0;
         m0 = rA0 * rB0;
         rA0 = pA0[19];
         rB0 = pB0[19];
         rC0_0 += m0;
         m0 = rA0 * rB0;
         rA0 = pA0[20];
         rB0 = pB0[20];
         rC0_0 += m0;
         m0 = rA0 * rB0;
         rA0 = pA0[21];
         rB0 = pB0[21];
         rC0_0 += m0;
         m0 = rA0 * rB0;
         rA0 = pA0[22];
         rB0 = pB0[22];
         pA0 += (22*(incAk0));
         pB0 += (22*(incBk0));
/*
 *       Drain pipe on last iteration of K-loop
 */
         rC0_0 += m0;
         m0 = rA0 * rB0;
         rC0_0 += m0;
         pA0 += incAk0;
         pB0 += incBk0;
         rB0 = alpha;
         rC0_0 *= rB0;
         *pC0 = rC0_0;
         pC0 += incCm;
         pA0 += incAm;
         pB0 += incBm;
      }
      while(pA0 != stM);
      pC0 += incCn;
      pA0 += incAn;
      pB0 += incBn;
   }
   while(pB0 != stN);
}
#ifdef incAm
   #undef incAm
#endif
#ifdef incAn
   #undef incAn
#endif
#ifdef incAk
   #undef incAk
#endif
#ifdef incBm
   #undef incBm
#endif
#ifdef incBn
   #undef incBn
#endif
#ifdef incBk
   #undef incBk
#endif
#ifdef incCm
   #undef incCm
#endif
#ifdef incCn
   #undef incCn
#endif
#ifdef incCk
   #undef incCk
#endif
#ifdef Mb
   #undef Mb
#endif
#ifdef Nb
   #undef Nb
#endif
#ifdef Kb
   #undef Kb
#endif
static void ATL_dJIK0x0x48TN2x1x24_aX_bX
   (const int M, const int N, const int K, const double alpha, const double * ATL_RESTRICT A, const int lda, const double * ATL_RESTRICT B, const int ldb, const double beta, double * ATL_RESTRICT C, const int ldc)
/*
 * matmul with TA=T, TB=N, MB=0, NB=0, KB=48, 
 * lda=0, ldb=0, ldc=0, mu=2, nu=1, ku=24, pf=0
 * Generated by ATLAS/tune/blas/gemm/emit_mm.c (3.9.23)
 */
{
   const int Mb = (M>>1)<<1;
   #define Nb N
   const double *ca=A, *cb=B;
   double *cc=C;
   const double *stM = A + (lda*Mb);
   const double *stN = B + (ldb*Nb);
   const double BetaAlpha = beta / alpha;
   #define incAk 24
   const int incAm = ((((lda) << 1)) - 48), incAn = -(Mb*lda);
   #define incBk 24
   const int incBm = -48, incBn = (ldb);
   const int incAk0 = ((incAk) / 24), incBk0 = ((incBk) / 24);
   #define incCm 2
   const int incCn = (ldc) - (Mb);
   double *pC0=C;
   const double *pA0=A, *pA1=pA0+(lda);
   const double *pB0=B;
   register int k;
   register double rA0, rA1;
   register double rB0;
   register double m0;
   register double rC0_0, rC1_0;
   if (pA0 != stM)
   {
      do /* N-loop */
      {
         do /* M-loop */
         {
            rA0 = BetaAlpha;
            rC0_0 = *pC0;
            rC0_0 *= rA0;
            rC1_0 = pC0[1];
            rC1_0 *= rA0;
/*
 *          Start pipeline
 */
            rA0 = *pA0;
            rB0 = *pB0;
            rA1 = *pA1;
            m0 = rA0 * rB0;

            for (k=0; k < 24; k += 24) /* easy loop to unroll */
            {
               rC0_0 += m0;
               m0 = rA1 * rB0;
               rA0 = pA0[1];
               rB0 = pB0[1];
               rA1 = pA1[1];
               rC1_0 += m0;
               m0 = rA0 * rB0;
               rC0_0 += m0;
               m0 = rA1 * rB0;
               rA0 = pA0[2];
               rB0 = pB0[2];
               rA1 = pA1[2];
               rC1_0 += m0;
               m0 = rA0 * rB0;
               rC0_0 += m0;
               m0 = rA1 * rB0;
               rA0 = pA0[3];
               rB0 = pB0[3];
               rA1 = pA1[3];
               rC1_0 += m0;
               m0 = rA0 * rB0;
               rC0_0 += m0;
               m0 = rA1 * rB0;
               rA0 = pA0[4];
               rB0 = pB0[4];
               rA1 = pA1[4];
               rC1_0 += m0;
               m0 = rA0 * rB0;
               rC0_0 += m0;
               m0 = rA1 * rB0;
               rA0 = pA0[5];
               rB0 = pB0[5];
               rA1 = pA1[5];
               rC1_0 += m0;
               m0 = rA0 * rB0;
               rC0_0 += m0;
               m0 = rA1 * rB0;
               rA0 = pA0[6];
               rB0 = pB0[6];
               rA1 = pA1[6];
               rC1_0 += m0;
               m0 = rA0 * rB0;
               rC0_0 += m0;
               m0 = rA1 * rB0;
               rA0 = pA0[7];
               rB0 = pB0[7];
               rA1 = pA1[7];
               rC1_0 += m0;
               m0 = rA0 * rB0;
               rC0_0 += m0;
               m0 = rA1 * rB0;
               rA0 = pA0[8];
               rB0 = pB0[8];
               rA1 = pA1[8];
               rC1_0 += m0;
               m0 = rA0 * rB0;
               rC0_0 += m0;
               m0 = rA1 * rB0;
               rA0 = pA0[9];
               rB0 = pB0[9];
               rA1 = pA1[9];
               rC1_0 += m0;
               m0 = rA0 * rB0;
               rC0_0 += m0;
               m0 = rA1 * rB0;
               rA0 = pA0[10];
               rB0 = pB0[10];
               rA1 = pA1[10];
               rC1_0 += m0;
               m0 = rA0 * rB0;
               rC0_0 += m0;
               m0 = rA1 * rB0;
               rA0 = pA0[11];
               rB0 = pB0[11];
               rA1 = pA1[11];
               rC1_0 += m0;
               m0 = rA0 * rB0;
               rC0_0 += m0;
               m0 = rA1 * rB0;
               rA0 = pA0[12];
               rB0 = pB0[12];
               rA1 = pA1[12];
               rC1_0 += m0;
               m0 = rA0 * rB0;
               rC0_0 += m0;
               m0 = rA1 * rB0;
               rA0 = pA0[13];
               rB0 = pB0[13];
               rA1 = pA1[13];
               rC1_0 += m0;
               m0 = rA0 * rB0;
               rC0_0 += m0;
               m0 = rA1 * rB0;
               rA0 = pA0[14];
               rB0 = pB0[14];
               rA1 = pA1[14];
               rC1_0 += m0;
               m0 = rA0 * rB0;
               rC0_0 += m0;
               m0 = rA1 * rB0;
               rA0 = pA0[15];
               rB0 = pB0[15];
               rA1 = pA1[15];
               rC1_0 += m0;
               m0 = rA0 * rB0;
               rC0_0 += m0;
               m0 = rA1 * rB0;
               rA0 = pA0[16];
               rB0 = pB0[16];
               rA1 = pA1[16];
               rC1_0 += m0;
               m0 = rA0 * rB0;
               rC0_0 += m0;
               m0 = rA1 * rB0;
               rA0 = pA0[17];
               rB0 = pB0[17];
               rA1 = pA1[17];
               rC1_0 += m0;
               m0 = rA0 * rB0;
               rC0_0 += m0;
               m0 = rA1 * rB0;
               rA0 = pA0[18];
               rB0 = pB0[18];
               rA1 = pA1[18];
               rC1_0 += m0;
               m0 = rA0 * rB0;
               rC0_0 += m0;
               m0 = rA1 * rB0;
               rA0 = pA0[19];
               rB0 = pB0[19];
               rA1 = pA1[19];
               rC1_0 += m0;
               m0 = rA0 * rB0;
               rC0_0 += m0;
               m0 = rA1 * rB0;
               rA0 = pA0[20];
               rB0 = pB0[20];
               rA1 = pA1[20];
               rC1_0 += m0;
               m0 = rA0 * rB0;
               rC0_0 += m0;
               m0 = rA1 * rB0;
               rA0 = pA0[21];
               rB0 = pB0[21];
               rA1 = pA1[21];
               rC1_0 += m0;
               m0 = rA0 * rB0;
               rC0_0 += m0;
               m0 = rA1 * rB0;
               rA0 = pA0[22];
               rB0 = pB0[22];
               rA1 = pA1[22];
               rC1_0 += m0;
               m0 = rA0 * rB0;
               rC0_0 += m0;
               m0 = rA1 * rB0;
               rA0 = pA0[23];
               rB0 = pB0[23];
               rA1 = pA1[23];
               rC1_0 += m0;
               m0 = rA0 * rB0;
               rC0_0 += m0;
               m0 = rA1 * rB0;
               rA0 = pA0[24];
               rB0 = pB0[24];
               rA1 = pA1[24];
               rC1_0 += m0;
               m0 = rA0 * rB0;
               pA0 += incAk;
               pA1 += incAk;
               pB0 += incBk;
            } /* end K-loop */
            rC0_0 += m0;
            m0 = rA1 * rB0;
            rA0 = pA0[1];
            rB0 = pB0[1];
            rA1 = pA1[1];
            rC1_0 += m0;
            m0 = rA0 * rB0;
            rC0_0 += m0;
            m0 = rA1 * rB0;
            rA0 = pA0[2];
            rB0 = pB0[2];
            rA1 = pA1[2];
            rC1_0 += m0;
            m0 = rA0 * rB0;
            rC0_0 += m0;
            m0 = rA1 * rB0;
            rA0 = pA0[3];
            rB0 = pB0[3];
            rA1 = pA1[3];
            rC1_0 += m0;
            m0 = rA0 * rB0;
            rC0_0 += m0;
            m0 = rA1 * rB0;
            rA0 = pA0[4];
            rB0 = pB0[4];
            rA1 = pA1[4];
            rC1_0 += m0;
            m0 = rA0 * rB0;
            rC0_0 += m0;
            m0 = rA1 * rB0;
            rA0 = pA0[5];
            rB0 = pB0[5];
            rA1 = pA1[5];
            rC1_0 += m0;
            m0 = rA0 * rB0;
            rC0_0 += m0;
            m0 = rA1 * rB0;
            rA0 = pA0[6];
            rB0 = pB0[6];
            rA1 = pA1[6];
            rC1_0 += m0;
            m0 = rA0 * rB0;
            rC0_0 += m0;
            m0 = rA1 * rB0;
            rA0 = pA0[7];
            rB0 = pB0[7];
            rA1 = pA1[7];
            rC1_0 += m0;
            m0 = rA0 * rB0;
            rC0_0 += m0;
            m0 = rA1 * rB0;
            rA0 = pA0[8];
            rB0 = pB0[8];
            rA1 = pA1[8];
            rC1_0 += m0;
            m0 = rA0 * rB0;
            rC0_0 += m0;
            m0 = rA1 * rB0;
            rA0 = pA0[9];
            rB0 = pB0[9];
            rA1 = pA1[9];
            rC1_0 += m0;
            m0 = rA0 * rB0;
            rC0_0 += m0;
            m0 = rA1 * rB0;
            rA0 = pA0[10];
            rB0 = pB0[10];
            rA1 = pA1[10];
            rC1_0 += m0;
            m0 = rA0 * rB0;
            rC0_0 += m0;
            m0 = rA1 * rB0;
            rA0 = pA0[11];
            rB0 = pB0[11];
            rA1 = pA1[11];
            rC1_0 += m0;
            m0 = rA0 * rB0;
            rC0_0 += m0;
            m0 = rA1 * rB0;
            rA0 = pA0[12];
            rB0 = pB0[12];
            rA1 = pA1[12];
            rC1_0 += m0;
            m0 = rA0 * rB0;
            rC0_0 += m0;
            m0 = rA1 * rB0;
            rA0 = pA0[13];
            rB0 = pB0[13];
            rA1 = pA1[13];
            rC1_0 += m0;
            m0 = rA0 * rB0;
            rC0_0 += m0;
            m0 = rA1 * rB0;
            rA0 = pA0[14];
            rB0 = pB0[14];
            rA1 = pA1[14];
            rC1_0 += m0;
            m0 = rA0 * rB0;
            rC0_0 += m0;
            m0 = rA1 * rB0;
            rA0 = pA0[15];
            rB0 = pB0[15];
            rA1 = pA1[15];
            rC1_0 += m0;
            m0 = rA0 * rB0;
            rC0_0 += m0;
            m0 = rA1 * rB0;
            rA0 = pA0[16];
            rB0 = pB0[16];
            rA1 = pA1[16];
            rC1_0 += m0;
            m0 = rA0 * rB0;
            rC0_0 += m0;
            m0 = rA1 * rB0;
            rA0 = pA0[17];
            rB0 = pB0[17];
            rA1 = pA1[17];
            rC1_0 += m0;
            m0 = rA0 * rB0;
            rC0_0 += m0;
            m0 = rA1 * rB0;
            rA0 = pA0[18];
            rB0 = pB0[18];
            rA1 = pA1[18];
            rC1_0 += m0;
            m0 = rA0 * rB0;
            rC0_0 += m0;
            m0 = rA1 * rB0;
            rA0 = pA0[19];
            rB0 = pB0[19];
            rA1 = pA1[19];
            rC1_0 += m0;
            m0 = rA0 * rB0;
            rC0_0 += m0;
            m0 = rA1 * rB0;
            rA0 = pA0[20];
            rB0 = pB0[20];
            rA1 = pA1[20];
            rC1_0 += m0;
            m0 = rA0 * rB0;
            rC0_0 += m0;
            m0 = rA1 * rB0;
            rA0 = pA0[21];
            rB0 = pB0[21];
            rA1 = pA1[21];
            rC1_0 += m0;
            m0 = rA0 * rB0;
            rC0_0 += m0;
            m0 = rA1 * rB0;
            rA0 = pA0[22];
            rB0 = pB0[22];
            rA1 = pA1[22];
            rC1_0 += m0;
            m0 = rA0 * rB0;
            rC0_0 += m0;
            m0 = rA1 * rB0;
            rA0 = pA0[23];
            rB0 = pB0[23];
            rA1 = pA1[23];
            rC1_0 += m0;
            m0 = rA0 * rB0;
            pA0 += (23*(incAk0));
            pA1 += (23*(incAk0));
            pB0 += (23*(incBk0));
/*
 *          Drain pipe on last iteration of K-loop
 */
            rC0_0 += m0;
            m0 = rA1 * rB0;
            rC1_0 += m0;
            pA0 += incAk0;
            pA1 += incAk0;
            pB0 += incBk0;
            rB0 = alpha;
            rC0_0 *= rB0;
            rC1_0 *= rB0;
            *pC0 = rC0_0;
            pC0[1] = rC1_0;
            pC0 += incCm;
            pA0 += incAm;
            pA1 += incAm;
            pB0 += incBm;
         }
         while(pA0 != stM);
         pC0 += incCn;
         pA0 += incAn;
         pA1 += incAn;
         pB0 += incBn;
      }
      while(pB0 != stN);
   }
   if (k=M-Mb)
      ATL_dJIK0x0x48TN1x1x24_aX_bX(k, N, 48, alpha, ca + (Mb*lda), lda, cb, ldb, beta, cc + (Mb), ldc);
}
#ifdef incAm
   #undef incAm
#endif
#ifdef incAn
   #undef incAn
#endif
#ifdef incAk
   #undef incAk
#endif
#ifdef incBm
   #undef incBm
#endif
#ifdef incBn
   #undef incBn
#endif
#ifdef incBk
   #undef incBk
#endif
#ifdef incCm
   #undef incCm
#endif
#ifdef incCn
   #undef incCn
#endif
#ifdef incCk
   #undef incCk
#endif
#ifdef Mb
   #undef Mb
#endif
#ifdef Nb
   #undef Nb
#endif
#ifdef Kb
   #undef Kb
#endif
#ifndef ATL_RESTRICT
#if defined(__STDC_VERSION__) && (__STDC_VERSION__/100 >= 1999)
   #define ATL_RESTRICT restrict
#else
   #define ATL_RESTRICT
#endif
#endif
static void ATL_dJIK0x0x48TN1x2x24_aX_bX
   (const int M, const int N, const int K, const double alpha, const double * ATL_RESTRICT A, const int lda, const double * ATL_RESTRICT B, const int ldb, const double beta, double * ATL_RESTRICT C, const int ldc)
/*
 * matmul with TA=T, TB=N, MB=0, NB=0, KB=48, 
 * lda=0, ldb=0, ldc=0, mu=1, nu=2, ku=24, pf=0
 * Generated by ATLAS/tune/blas/gemm/emit_mm.c (3.9.23)
 */
{
   #define Mb M
   const int Nb = (N>>1)<<1;
   const double *ca=A, *cb=B;
   double *cc=C;
   const double *stM = A + (lda*Mb);
   const double *stN = B + (ldb*Nb);
   const double BetaAlpha = beta / alpha;
   #define incAk 24
   const int incAm = ((lda) - 48), incAn = -(Mb*lda);
   #define incBk 24
   const int incBm = -48, incBn = (((ldb) << 1));
   const int incAk0 = ((incAk) / 24), incBk0 = ((incBk) / 24);
   #define incCm 1
   const int incCn = (((ldc) << 1)) - (Mb);
   double *pC0=C, *pC1=pC0+(ldc);
   const double *pA0=A;
   const double *pB0=B, *pB1=pB0+(ldb);
   register int k;
   register double rA0;
   register double rB0, rB1;
   register double m0;
   register double rC0_0, rC0_1;
   if (pB0 != stN)
   {
      do /* N-loop */
      {
         do /* M-loop */
         {
            rA0 = BetaAlpha;
            rC0_0 = *pC0;
            rC0_0 *= rA0;
            rC0_1 = *pC1;
            rC0_1 *= rA0;
/*
 *          Start pipeline
 */
            rA0 = *pA0;
            rB0 = *pB0;
            rB1 = *pB1;
            m0 = rA0 * rB0;

            for (k=0; k < 24; k += 24) /* easy loop to unroll */
            {
               rC0_0 += m0;
               m0 = rA0 * rB1;
               rA0 = pA0[1];
               rB0 = pB0[1];
               rB1 = pB1[1];
               rC0_1 += m0;
               m0 = rA0 * rB0;
               rC0_0 += m0;
               m0 = rA0 * rB1;
               rA0 = pA0[2];
               rB0 = pB0[2];
               rB1 = pB1[2];
               rC0_1 += m0;
               m0 = rA0 * rB0;
               rC0_0 += m0;
               m0 = rA0 * rB1;
               rA0 = pA0[3];
               rB0 = pB0[3];
               rB1 = pB1[3];
               rC0_1 += m0;
               m0 = rA0 * rB0;
               rC0_0 += m0;
               m0 = rA0 * rB1;
               rA0 = pA0[4];
               rB0 = pB0[4];
               rB1 = pB1[4];
               rC0_1 += m0;
               m0 = rA0 * rB0;
               rC0_0 += m0;
               m0 = rA0 * rB1;
               rA0 = pA0[5];
               rB0 = pB0[5];
               rB1 = pB1[5];
               rC0_1 += m0;
               m0 = rA0 * rB0;
               rC0_0 += m0;
               m0 = rA0 * rB1;
               rA0 = pA0[6];
               rB0 = pB0[6];
               rB1 = pB1[6];
               rC0_1 += m0;
               m0 = rA0 * rB0;
               rC0_0 += m0;
               m0 = rA0 * rB1;
               rA0 = pA0[7];
               rB0 = pB0[7];
               rB1 = pB1[7];
               rC0_1 += m0;
               m0 = rA0 * rB0;
               rC0_0 += m0;
               m0 = rA0 * rB1;
               rA0 = pA0[8];
               rB0 = pB0[8];
               rB1 = pB1[8];
               rC0_1 += m0;
               m0 = rA0 * rB0;
               rC0_0 += m0;
               m0 = rA0 * rB1;
               rA0 = pA0[9];
               rB0 = pB0[9];
               rB1 = pB1[9];
               rC0_1 += m0;
               m0 = rA0 * rB0;
               rC0_0 += m0;
               m0 = rA0 * rB1;
               rA0 = pA0[10];
               rB0 = pB0[10];
               rB1 = pB1[10];
               rC0_1 += m0;
               m0 = rA0 * rB0;
               rC0_0 += m0;
               m0 = rA0 * rB1;
               rA0 = pA0[11];
               rB0 = pB0[11];
               rB1 = pB1[11];
               rC0_1 += m0;
               m0 = rA0 * rB0;
               rC0_0 += m0;
               m0 = rA0 * rB1;
               rA0 = pA0[12];
               rB0 = pB0[12];
               rB1 = pB1[12];
               rC0_1 += m0;
               m0 = rA0 * rB0;
               rC0_0 += m0;
               m0 = rA0 * rB1;
               rA0 = pA0[13];
               rB0 = pB0[13];
               rB1 = pB1[13];
               rC0_1 += m0;
               m0 = rA0 * rB0;
               rC0_0 += m0;
               m0 = rA0 * rB1;
               rA0 = pA0[14];
               rB0 = pB0[14];
               rB1 = pB1[14];
               rC0_1 += m0;
               m0 = rA0 * rB0;
               rC0_0 += m0;
               m0 = rA0 * rB1;
               rA0 = pA0[15];
               rB0 = pB0[15];
               rB1 = pB1[15];
               rC0_1 += m0;
               m0 = rA0 * rB0;
               rC0_0 += m0;
               m0 = rA0 * rB1;
               rA0 = pA0[16];
               rB0 = pB0[16];
               rB1 = pB1[16];
               rC0_1 += m0;
               m0 = rA0 * rB0;
               rC0_0 += m0;
               m0 = rA0 * rB1;
               rA0 = pA0[17];
               rB0 = pB0[17];
               rB1 = pB1[17];
               rC0_1 += m0;
               m0 = rA0 * rB0;
               rC0_0 += m0;
               m0 = rA0 * rB1;
               rA0 = pA0[18];
               rB0 = pB0[18];
               rB1 = pB1[18];
               rC0_1 += m0;
               m0 = rA0 * rB0;
               rC0_0 += m0;
               m0 = rA0 * rB1;
               rA0 = pA0[19];
               rB0 = pB0[19];
               rB1 = pB1[19];
               rC0_1 += m0;
               m0 = rA0 * rB0;
               rC0_0 += m0;
               m0 = rA0 * rB1;
               rA0 = pA0[20];
               rB0 = pB0[20];
               rB1 = pB1[20];
               rC0_1 += m0;
               m0 = rA0 * rB0;
               rC0_0 += m0;
               m0 = rA0 * rB1;
               rA0 = pA0[21];
               rB0 = pB0[21];
               rB1 = pB1[21];
               rC0_1 += m0;
               m0 = rA0 * rB0;
               rC0_0 += m0;
               m0 = rA0 * rB1;
               rA0 = pA0[22];
               rB0 = pB0[22];
               rB1 = pB1[22];
               rC0_1 += m0;
               m0 = rA0 * rB0;
               rC0_0 += m0;
               m0 = rA0 * rB1;
               rA0 = pA0[23];
               rB0 = pB0[23];
               rB1 = pB1[23];
               rC0_1 += m0;
               m0 = rA0 * rB0;
               rC0_0 += m0;
               m0 = rA0 * rB1;
               rA0 = pA0[24];
               rB0 = pB0[24];
               rB1 = pB1[24];
               rC0_1 += m0;
               m0 = rA0 * rB0;
               pA0 += incAk;
               pB0 += incBk;
               pB1 += incBk;
            } /* end K-loop */
            rC0_0 += m0;
            m0 = rA0 * rB1;
            rA0 = pA0[1];
            rB0 = pB0[1];
            rB1 = pB1[1];
            rC0_1 += m0;
            m0 = rA0 * rB0;
            rC0_0 += m0;
            m0 = rA0 * rB1;
            rA0 = pA0[2];
            rB0 = pB0[2];
            rB1 = pB1[2];
            rC0_1 += m0;
            m0 = rA0 * rB0;
            rC0_0 += m0;
            m0 = rA0 * rB1;
            rA0 = pA0[3];
            rB0 = pB0[3];
            rB1 = pB1[3];
            rC0_1 += m0;
            m0 = rA0 * rB0;
            rC0_0 += m0;
            m0 = rA0 * rB1;
            rA0 = pA0[4];
            rB0 = pB0[4];
            rB1 = pB1[4];
            rC0_1 += m0;
            m0 = rA0 * rB0;
            rC0_0 += m0;
            m0 = rA0 * rB1;
            rA0 = pA0[5];
            rB0 = pB0[5];
            rB1 = pB1[5];
            rC0_1 += m0;
            m0 = rA0 * rB0;
            rC0_0 += m0;
            m0 = rA0 * rB1;
            rA0 = pA0[6];
            rB0 = pB0[6];
            rB1 = pB1[6];
            rC0_1 += m0;
            m0 = rA0 * rB0;
            rC0_0 += m0;
            m0 = rA0 * rB1;
            rA0 = pA0[7];
            rB0 = pB0[7];
            rB1 = pB1[7];
            rC0_1 += m0;
            m0 = rA0 * rB0;
            rC0_0 += m0;
            m0 = rA0 * rB1;
            rA0 = pA0[8];
            rB0 = pB0[8];
            rB1 = pB1[8];
            rC0_1 += m0;
            m0 = rA0 * rB0;
            rC0_0 += m0;
            m0 = rA0 * rB1;
            rA0 = pA0[9];
            rB0 = pB0[9];
            rB1 = pB1[9];
            rC0_1 += m0;
            m0 = rA0 * rB0;
            rC0_0 += m0;
            m0 = rA0 * rB1;
            rA0 = pA0[10];
            rB0 = pB0[10];
            rB1 = pB1[10];
            rC0_1 += m0;
            m0 = rA0 * rB0;
            rC0_0 += m0;
            m0 = rA0 * rB1;
            rA0 = pA0[11];
            rB0 = pB0[11];
            rB1 = pB1[11];
            rC0_1 += m0;
            m0 = rA0 * rB0;
            rC0_0 += m0;
            m0 = rA0 * rB1;
            rA0 = pA0[12];
            rB0 = pB0[12];
            rB1 = pB1[12];
            rC0_1 += m0;
            m0 = rA0 * rB0;
            rC0_0 += m0;
            m0 = rA0 * rB1;
            rA0 = pA0[13];
            rB0 = pB0[13];
            rB1 = pB1[13];
            rC0_1 += m0;
            m0 = rA0 * rB0;
            rC0_0 += m0;
            m0 = rA0 * rB1;
            rA0 = pA0[14];
            rB0 = pB0[14];
            rB1 = pB1[14];
            rC0_1 += m0;
            m0 = rA0 * rB0;
            rC0_0 += m0;
            m0 = rA0 * rB1;
            rA0 = pA0[15];
            rB0 = pB0[15];
            rB1 = pB1[15];
            rC0_1 += m0;
            m0 = rA0 * rB0;
            rC0_0 += m0;
            m0 = rA0 * rB1;
            rA0 = pA0[16];
            rB0 = pB0[16];
            rB1 = pB1[16];
            rC0_1 += m0;
            m0 = rA0 * rB0;
            rC0_0 += m0;
            m0 = rA0 * rB1;
            rA0 = pA0[17];
            rB0 = pB0[17];
            rB1 = pB1[17];
            rC0_1 += m0;
            m0 = rA0 * rB0;
            rC0_0 += m0;
            m0 = rA0 * rB1;
            rA0 = pA0[18];
            rB0 = pB0[18];
            rB1 = pB1[18];
            rC0_1 += m0;
            m0 = rA0 * rB0;
            rC0_0 += m0;
            m0 = rA0 * rB1;
            rA0 = pA0[19];
            rB0 = pB0[19];
            rB1 = pB1[19];
            rC0_1 += m0;
            m0 = rA0 * rB0;
            rC0_0 += m0;
            m0 = rA0 * rB1;
            rA0 = pA0[20];
            rB0 = pB0[20];
            rB1 = pB1[20];
            rC0_1 += m0;
            m0 = rA0 * rB0;
            rC0_0 += m0;
            m0 = rA0 * rB1;
            rA0 = pA0[21];
            rB0 = pB0[21];
            rB1 = pB1[21];
            rC0_1 += m0;
            m0 = rA0 * rB0;
            rC0_0 += m0;
            m0 = rA0 * rB1;
            rA0 = pA0[22];
            rB0 = pB0[22];
            rB1 = pB1[22];
            rC0_1 += m0;
            m0 = rA0 * rB0;
            rC0_0 += m0;
            m0 = rA0 * rB1;
            rA0 = pA0[23];
            rB0 = pB0[23];
            rB1 = pB1[23];
            rC0_1 += m0;
            m0 = rA0 * rB0;
            pA0 += (23*(incAk0));
            pB0 += (23*(incBk0));
            pB1 += (23*(incBk0));
/*
 *          Drain pipe on last iteration of K-loop
 */
            rC0_0 += m0;
            m0 = rA0 * rB1;
            rC0_1 += m0;
            pA0 += incAk0;
            pB0 += incBk0;
            pB1 += incBk0;
            rB0 = alpha;
            rC0_0 *= rB0;
            rC0_1 *= rB0;
            *pC0 = rC0_0;
            *pC1 = rC0_1;
            pC0 += incCm;
            pC1 += incCm;
            pA0 += incAm;
            pB0 += incBm;
            pB1 += incBm;
         }
         while(pA0 != stM);
         pC0 += incCn;
         pC1 += incCn;
         pA0 += incAn;
         pB0 += incBn;
         pB1 += incBn;
      }
      while(pB0 != stN);
   }
   if (k=N-Nb)
      ATL_dJIK0x0x48TN1x1x24_aX_bX(M, k, 48, alpha, ca, lda, cb + (Nb*ldb), ldb, beta, cc + (Nb*ldc), ldc);
}
#ifdef incAm
   #undef incAm
#endif
#ifdef incAn
   #undef incAn
#endif
#ifdef incAk
   #undef incAk
#endif
#ifdef incBm
   #undef incBm
#endif
#ifdef incBn
   #undef incBn
#endif
#ifdef incBk
   #undef incBk
#endif
#ifdef incCm
   #undef incCm
#endif
#ifdef incCn
   #undef incCn
#endif
#ifdef incCk
   #undef incCk
#endif
#ifdef Mb
   #undef Mb
#endif
#ifdef Nb
   #undef Nb
#endif
#ifdef Kb
   #undef Kb
#endif
void ATL_dJIK0x0x48TN0x0x0_aX_bX
   (const int M, const int N, const int K, const double alpha, const double * ATL_RESTRICT A, const int lda, const double * ATL_RESTRICT B, const int ldb, const double beta, double * ATL_RESTRICT C, const int ldc)
/*
 * matmul with TA=T, TB=N, MB=0, NB=0, KB=48, 
 * lda=0, ldb=0, ldc=0, mu=2, nu=2, ku=24, pf=0
 * Generated by ATLAS/tune/blas/gemm/emit_mm.c (3.9.23)
 */
{
   const int Mb = (M>>1)<<1;
   const int Nb = (N>>1)<<1;
   const double *ca=A, *cb=B;
   double *cc=C;
   const double *stM = A + (lda*Mb);
   const double *stN = B + (ldb*Nb);
   const double BetaAlpha = beta / alpha;
   #define incAk 24
   const int incAm = ((((lda) << 1)) - 48), incAn = -(Mb*lda);
   #define incBk 24
   const int incBm = -48, incBn = (((ldb) << 1));
   const int incAk0 = ((incAk) / 24), incBk0 = ((incBk) / 24);
   #define incCm 2
   const int incCn = (((ldc) << 1)) - (Mb);
   double *pC0=C, *pC1=pC0+(ldc);
   const double *pA0=A, *pA1=pA0+(lda);
   const double *pB0=B, *pB1=pB0+(ldb);
   register int k;
   register double rA0, rA1;
   register double rB0, rB1;
   register double m0;
   register double rC0_0, rC1_0, rC0_1, rC1_1;
   if (pA0 != stM)
   {
      if (pB0 != stN)
      {
         do /* N-loop */
         {
            do /* M-loop */
            {
               rA0 = BetaAlpha;
               rC0_0 = *pC0;
               rC0_0 *= rA0;
               rC1_0 = pC0[1];
               rC1_0 *= rA0;
               rC0_1 = *pC1;
               rC0_1 *= rA0;
               rC1_1 = pC1[1];
               rC1_1 *= rA0;
/*
 *             Start pipeline
 */
               rA0 = *pA0;
               rB0 = *pB0;
               rA1 = *pA1;
               m0 = rA0 * rB0;
               rB1 = *pB1;

               for (k=0; k < 24; k += 24) /* easy loop to unroll */
               {
                  rC0_0 += m0;
                  m0 = rA1 * rB0;
                  rC1_0 += m0;
                  m0 = rA0 * rB1;
                  rC0_1 += m0;
                  m0 = rA1 * rB1;
                  rA0 = pA0[1];
                  rB0 = pB0[1];
                  rA1 = pA1[1];
                  rB1 = pB1[1];
                  rC1_1 += m0;
                  m0 = rA0 * rB0;
                  rC0_0 += m0;
                  m0 = rA1 * rB0;
                  rC1_0 += m0;
                  m0 = rA0 * rB1;
                  rC0_1 += m0;
                  m0 = rA1 * rB1;
                  rA0 = pA0[2];
                  rB0 = pB0[2];
                  rA1 = pA1[2];
                  rB1 = pB1[2];
                  rC1_1 += m0;
                  m0 = rA0 * rB0;
                  rC0_0 += m0;
                  m0 = rA1 * rB0;
                  rC1_0 += m0;
                  m0 = rA0 * rB1;
                  rC0_1 += m0;
                  m0 = rA1 * rB1;
                  rA0 = pA0[3];
                  rB0 = pB0[3];
                  rA1 = pA1[3];
                  rB1 = pB1[3];
                  rC1_1 += m0;
                  m0 = rA0 * rB0;
                  rC0_0 += m0;
                  m0 = rA1 * rB0;
                  rC1_0 += m0;
                  m0 = rA0 * rB1;
                  rC0_1 += m0;
                  m0 = rA1 * rB1;
                  rA0 = pA0[4];
                  rB0 = pB0[4];
                  rA1 = pA1[4];
                  rB1 = pB1[4];
                  rC1_1 += m0;
                  m0 = rA0 * rB0;
                  rC0_0 += m0;
                  m0 = rA1 * rB0;
                  rC1_0 += m0;
                  m0 = rA0 * rB1;
                  rC0_1 += m0;
                  m0 = rA1 * rB1;
                  rA0 = pA0[5];
                  rB0 = pB0[5];
                  rA1 = pA1[5];
                  rB1 = pB1[5];
                  rC1_1 += m0;
                  m0 = rA0 * rB0;
                  rC0_0 += m0;
                  m0 = rA1 * rB0;
                  rC1_0 += m0;
                  m0 = rA0 * rB1;
                  rC0_1 += m0;
                  m0 = rA1 * rB1;
                  rA0 = pA0[6];
                  rB0 = pB0[6];
                  rA1 = pA1[6];
                  rB1 = pB1[6];
                  rC1_1 += m0;
                  m0 = rA0 * rB0;
                  rC0_0 += m0;
                  m0 = rA1 * rB0;
                  rC1_0 += m0;
                  m0 = rA0 * rB1;
                  rC0_1 += m0;
                  m0 = rA1 * rB1;
                  rA0 = pA0[7];
                  rB0 = pB0[7];
                  rA1 = pA1[7];
                  rB1 = pB1[7];
                  rC1_1 += m0;
                  m0 = rA0 * rB0;
                  rC0_0 += m0;
                  m0 = rA1 * rB0;
                  rC1_0 += m0;
                  m0 = rA0 * rB1;
                  rC0_1 += m0;
                  m0 = rA1 * rB1;
                  rA0 = pA0[8];
                  rB0 = pB0[8];
                  rA1 = pA1[8];
                  rB1 = pB1[8];
                  rC1_1 += m0;
                  m0 = rA0 * rB0;
                  rC0_0 += m0;
                  m0 = rA1 * rB0;
                  rC1_0 += m0;
                  m0 = rA0 * rB1;
                  rC0_1 += m0;
                  m0 = rA1 * rB1;
                  rA0 = pA0[9];
                  rB0 = pB0[9];
                  rA1 = pA1[9];
                  rB1 = pB1[9];
                  rC1_1 += m0;
                  m0 = rA0 * rB0;
                  rC0_0 += m0;
                  m0 = rA1 * rB0;
                  rC1_0 += m0;
                  m0 = rA0 * rB1;
                  rC0_1 += m0;
                  m0 = rA1 * rB1;
                  rA0 = pA0[10];
                  rB0 = pB0[10];
                  rA1 = pA1[10];
                  rB1 = pB1[10];
                  rC1_1 += m0;
                  m0 = rA0 * rB0;
                  rC0_0 += m0;
                  m0 = rA1 * rB0;
                  rC1_0 += m0;
                  m0 = rA0 * rB1;
                  rC0_1 += m0;
                  m0 = rA1 * rB1;
                  rA0 = pA0[11];
                  rB0 = pB0[11];
                  rA1 = pA1[11];
                  rB1 = pB1[11];
                  rC1_1 += m0;
                  m0 = rA0 * rB0;
                  rC0_0 += m0;
                  m0 = rA1 * rB0;
                  rC1_0 += m0;
                  m0 = rA0 * rB1;
                  rC0_1 += m0;
                  m0 = rA1 * rB1;
                  rA0 = pA0[12];
                  rB0 = pB0[12];
                  rA1 = pA1[12];
                  rB1 = pB1[12];
                  rC1_1 += m0;
                  m0 = rA0 * rB0;
                  rC0_0 += m0;
                  m0 = rA1 * rB0;
                  rC1_0 += m0;
                  m0 = rA0 * rB1;
                  rC0_1 += m0;
                  m0 = rA1 * rB1;
                  rA0 = pA0[13];
                  rB0 = pB0[13];
                  rA1 = pA1[13];
                  rB1 = pB1[13];
                  rC1_1 += m0;
                  m0 = rA0 * rB0;
                  rC0_0 += m0;
                  m0 = rA1 * rB0;
                  rC1_0 += m0;
                  m0 = rA0 * rB1;
                  rC0_1 += m0;
                  m0 = rA1 * rB1;
                  rA0 = pA0[14];
                  rB0 = pB0[14];
                  rA1 = pA1[14];
                  rB1 = pB1[14];
                  rC1_1 += m0;
                  m0 = rA0 * rB0;
                  rC0_0 += m0;
                  m0 = rA1 * rB0;
                  rC1_0 += m0;
                  m0 = rA0 * rB1;
                  rC0_1 += m0;
                  m0 = rA1 * rB1;
                  rA0 = pA0[15];
                  rB0 = pB0[15];
                  rA1 = pA1[15];
                  rB1 = pB1[15];
                  rC1_1 += m0;
                  m0 = rA0 * rB0;
                  rC0_0 += m0;
                  m0 = rA1 * rB0;
                  rC1_0 += m0;
                  m0 = rA0 * rB1;
                  rC0_1 += m0;
                  m0 = rA1 * rB1;
                  rA0 = pA0[16];
                  rB0 = pB0[16];
                  rA1 = pA1[16];
                  rB1 = pB1[16];
                  rC1_1 += m0;
                  m0 = rA0 * rB0;
                  rC0_0 += m0;
                  m0 = rA1 * rB0;
                  rC1_0 += m0;
                  m0 = rA0 * rB1;
                  rC0_1 += m0;
                  m0 = rA1 * rB1;
                  rA0 = pA0[17];
                  rB0 = pB0[17];
                  rA1 = pA1[17];
                  rB1 = pB1[17];
                  rC1_1 += m0;
                  m0 = rA0 * rB0;
                  rC0_0 += m0;
                  m0 = rA1 * rB0;
                  rC1_0 += m0;
                  m0 = rA0 * rB1;
                  rC0_1 += m0;
                  m0 = rA1 * rB1;
                  rA0 = pA0[18];
                  rB0 = pB0[18];
                  rA1 = pA1[18];
                  rB1 = pB1[18];
                  rC1_1 += m0;
                  m0 = rA0 * rB0;
                  rC0_0 += m0;
                  m0 = rA1 * rB0;
                  rC1_0 += m0;
                  m0 = rA0 * rB1;
                  rC0_1 += m0;
                  m0 = rA1 * rB1;
                  rA0 = pA0[19];
                  rB0 = pB0[19];
                  rA1 = pA1[19];
                  rB1 = pB1[19];
                  rC1_1 += m0;
                  m0 = rA0 * rB0;
                  rC0_0 += m0;
                  m0 = rA1 * rB0;
                  rC1_0 += m0;
                  m0 = rA0 * rB1;
                  rC0_1 += m0;
                  m0 = rA1 * rB1;
                  rA0 = pA0[20];
                  rB0 = pB0[20];
                  rA1 = pA1[20];
                  rB1 = pB1[20];
                  rC1_1 += m0;
                  m0 = rA0 * rB0;
                  rC0_0 += m0;
                  m0 = rA1 * rB0;
                  rC1_0 += m0;
                  m0 = rA0 * rB1;
                  rC0_1 += m0;
                  m0 = rA1 * rB1;
                  rA0 = pA0[21];
                  rB0 = pB0[21];
                  rA1 = pA1[21];
                  rB1 = pB1[21];
                  rC1_1 += m0;
                  m0 = rA0 * rB0;
                  rC0_0 += m0;
                  m0 = rA1 * rB0;
                  rC1_0 += m0;
                  m0 = rA0 * rB1;
                  rC0_1 += m0;
                  m0 = rA1 * rB1;
                  rA0 = pA0[22];
                  rB0 = pB0[22];
                  rA1 = pA1[22];
                  rB1 = pB1[22];
                  rC1_1 += m0;
                  m0 = rA0 * rB0;
                  rC0_0 += m0;
                  m0 = rA1 * rB0;
                  rC1_0 += m0;
                  m0 = rA0 * rB1;
                  rC0_1 += m0;
                  m0 = rA1 * rB1;
                  rA0 = pA0[23];
                  rB0 = pB0[23];
                  rA1 = pA1[23];
                  rB1 = pB1[23];
                  rC1_1 += m0;
                  m0 = rA0 * rB0;
                  rC0_0 += m0;
                  m0 = rA1 * rB0;
                  rC1_0 += m0;
                  m0 = rA0 * rB1;
                  rC0_1 += m0;
                  m0 = rA1 * rB1;
                  rA0 = pA0[24];
                  rB0 = pB0[24];
                  rA1 = pA1[24];
                  rB1 = pB1[24];
                  rC1_1 += m0;
                  m0 = rA0 * rB0;
                  pA0 += incAk;
                  pA1 += incAk;
                  pB0 += incBk;
                  pB1 += incBk;
               } /* end K-loop */
               rC0_0 += m0;
               m0 = rA1 * rB0;
               rC1_0 += m0;
               m0 = rA0 * rB1;
               rC0_1 += m0;
               m0 = rA1 * rB1;
               rA0 = pA0[1];
               rB0 = pB0[1];
               rA1 = pA1[1];
               rB1 = pB1[1];
               rC1_1 += m0;
               m0 = rA0 * rB0;
               rC0_0 += m0;
               m0 = rA1 * rB0;
               rC1_0 += m0;
               m0 = rA0 * rB1;
               rC0_1 += m0;
               m0 = rA1 * rB1;
               rA0 = pA0[2];
               rB0 = pB0[2];
               rA1 = pA1[2];
               rB1 = pB1[2];
               rC1_1 += m0;
               m0 = rA0 * rB0;
               rC0_0 += m0;
               m0 = rA1 * rB0;
               rC1_0 += m0;
               m0 = rA0 * rB1;
               rC0_1 += m0;
               m0 = rA1 * rB1;
               rA0 = pA0[3];
               rB0 = pB0[3];
               rA1 = pA1[3];
               rB1 = pB1[3];
               rC1_1 += m0;
               m0 = rA0 * rB0;
               rC0_0 += m0;
               m0 = rA1 * rB0;
               rC1_0 += m0;
               m0 = rA0 * rB1;
               rC0_1 += m0;
               m0 = rA1 * rB1;
               rA0 = pA0[4];
               rB0 = pB0[4];
               rA1 = pA1[4];
               rB1 = pB1[4];
               rC1_1 += m0;
               m0 = rA0 * rB0;
               rC0_0 += m0;
               m0 = rA1 * rB0;
               rC1_0 += m0;
               m0 = rA0 * rB1;
               rC0_1 += m0;
               m0 = rA1 * rB1;
               rA0 = pA0[5];
               rB0 = pB0[5];
               rA1 = pA1[5];
               rB1 = pB1[5];
               rC1_1 += m0;
               m0 = rA0 * rB0;
               rC0_0 += m0;
               m0 = rA1 * rB0;
               rC1_0 += m0;
               m0 = rA0 * rB1;
               rC0_1 += m0;
               m0 = rA1 * rB1;
               rA0 = pA0[6];
               rB0 = pB0[6];
               rA1 = pA1[6];
               rB1 = pB1[6];
               rC1_1 += m0;
               m0 = rA0 * rB0;
               rC0_0 += m0;
               m0 = rA1 * rB0;
               rC1_0 += m0;
               m0 = rA0 * rB1;
               rC0_1 += m0;
               m0 = rA1 * rB1;
               rA0 = pA0[7];
               rB0 = pB0[7];
               rA1 = pA1[7];
               rB1 = pB1[7];
               rC1_1 += m0;
               m0 = rA0 * rB0;
               rC0_0 += m0;
               m0 = rA1 * rB0;
               rC1_0 += m0;
               m0 = rA0 * rB1;
               rC0_1 += m0;
               m0 = rA1 * rB1;
               rA0 = pA0[8];
               rB0 = pB0[8];
               rA1 = pA1[8];
               rB1 = pB1[8];
               rC1_1 += m0;
               m0 = rA0 * rB0;
               rC0_0 += m0;
               m0 = rA1 * rB0;
               rC1_0 += m0;
               m0 = rA0 * rB1;
               rC0_1 += m0;
               m0 = rA1 * rB1;
               rA0 = pA0[9];
               rB0 = pB0[9];
               rA1 = pA1[9];
               rB1 = pB1[9];
               rC1_1 += m0;
               m0 = rA0 * rB0;
               rC0_0 += m0;
               m0 = rA1 * rB0;
               rC1_0 += m0;
               m0 = rA0 * rB1;
               rC0_1 += m0;
               m0 = rA1 * rB1;
               rA0 = pA0[10];
               rB0 = pB0[10];
               rA1 = pA1[10];
               rB1 = pB1[10];
               rC1_1 += m0;
               m0 = rA0 * rB0;
               rC0_0 += m0;
               m0 = rA1 * rB0;
               rC1_0 += m0;
               m0 = rA0 * rB1;
               rC0_1 += m0;
               m0 = rA1 * rB1;
               rA0 = pA0[11];
               rB0 = pB0[11];
               rA1 = pA1[11];
               rB1 = pB1[11];
               rC1_1 += m0;
               m0 = rA0 * rB0;
               rC0_0 += m0;
               m0 = rA1 * rB0;
               rC1_0 += m0;
               m0 = rA0 * rB1;
               rC0_1 += m0;
               m0 = rA1 * rB1;
               rA0 = pA0[12];
               rB0 = pB0[12];
               rA1 = pA1[12];
               rB1 = pB1[12];
               rC1_1 += m0;
               m0 = rA0 * rB0;
               rC0_0 += m0;
               m0 = rA1 * rB0;
               rC1_0 += m0;
               m0 = rA0 * rB1;
               rC0_1 += m0;
               m0 = rA1 * rB1;
               rA0 = pA0[13];
               rB0 = pB0[13];
               rA1 = pA1[13];
               rB1 = pB1[13];
               rC1_1 += m0;
               m0 = rA0 * rB0;
               rC0_0 += m0;
               m0 = rA1 * rB0;
               rC1_0 += m0;
               m0 = rA0 * rB1;
               rC0_1 += m0;
               m0 = rA1 * rB1;
               rA0 = pA0[14];
               rB0 = pB0[14];
               rA1 = pA1[14];
               rB1 = pB1[14];
               rC1_1 += m0;
               m0 = rA0 * rB0;
               rC0_0 += m0;
               m0 = rA1 * rB0;
               rC1_0 += m0;
               m0 = rA0 * rB1;
               rC0_1 += m0;
               m0 = rA1 * rB1;
               rA0 = pA0[15];
               rB0 = pB0[15];
               rA1 = pA1[15];
               rB1 = pB1[15];
               rC1_1 += m0;
               m0 = rA0 * rB0;
               rC0_0 += m0;
               m0 = rA1 * rB0;
               rC1_0 += m0;
               m0 = rA0 * rB1;
               rC0_1 += m0;
               m0 = rA1 * rB1;
               rA0 = pA0[16];
               rB0 = pB0[16];
               rA1 = pA1[16];
               rB1 = pB1[16];
               rC1_1 += m0;
               m0 = rA0 * rB0;
               rC0_0 += m0;
               m0 = rA1 * rB0;
               rC1_0 += m0;
               m0 = rA0 * rB1;
               rC0_1 += m0;
               m0 = rA1 * rB1;
               rA0 = pA0[17];
               rB0 = pB0[17];
               rA1 = pA1[17];
               rB1 = pB1[17];
               rC1_1 += m0;
               m0 = rA0 * rB0;
               rC0_0 += m0;
               m0 = rA1 * rB0;
               rC1_0 += m0;
               m0 = rA0 * rB1;
               rC0_1 += m0;
               m0 = rA1 * rB1;
               rA0 = pA0[18];
               rB0 = pB0[18];
               rA1 = pA1[18];
               rB1 = pB1[18];
               rC1_1 += m0;
               m0 = rA0 * rB0;
               rC0_0 += m0;
               m0 = rA1 * rB0;
               rC1_0 += m0;
               m0 = rA0 * rB1;
               rC0_1 += m0;
               m0 = rA1 * rB1;
               rA0 = pA0[19];
               rB0 = pB0[19];
               rA1 = pA1[19];
               rB1 = pB1[19];
               rC1_1 += m0;
               m0 = rA0 * rB0;
               rC0_0 += m0;
               m0 = rA1 * rB0;
               rC1_0 += m0;
               m0 = rA0 * rB1;
               rC0_1 += m0;
               m0 = rA1 * rB1;
               rA0 = pA0[20];
               rB0 = pB0[20];
               rA1 = pA1[20];
               rB1 = pB1[20];
               rC1_1 += m0;
               m0 = rA0 * rB0;
               rC0_0 += m0;
               m0 = rA1 * rB0;
               rC1_0 += m0;
               m0 = rA0 * rB1;
               rC0_1 += m0;
               m0 = rA1 * rB1;
               rA0 = pA0[21];
               rB0 = pB0[21];
               rA1 = pA1[21];
               rB1 = pB1[21];
               rC1_1 += m0;
               m0 = rA0 * rB0;
               rC0_0 += m0;
               m0 = rA1 * rB0;
               rC1_0 += m0;
               m0 = rA0 * rB1;
               rC0_1 += m0;
               m0 = rA1 * rB1;
               rA0 = pA0[22];
               rB0 = pB0[22];
               rA1 = pA1[22];
               rB1 = pB1[22];
               rC1_1 += m0;
               m0 = rA0 * rB0;
               rC0_0 += m0;
               m0 = rA1 * rB0;
               rC1_0 += m0;
               m0 = rA0 * rB1;
               rC0_1 += m0;
               m0 = rA1 * rB1;
               rA0 = pA0[23];
               rB0 = pB0[23];
               rA1 = pA1[23];
               rB1 = pB1[23];
               rC1_1 += m0;
               m0 = rA0 * rB0;
               pA0 += (23*(incAk0));
               pA1 += (23*(incAk0));
               pB0 += (23*(incBk0));
               pB1 += (23*(incBk0));
/*
 *             Drain pipe on last iteration of K-loop
 */
               rC0_0 += m0;
               m0 = rA1 * rB0;
               rC1_0 += m0;
               m0 = rA0 * rB1;
               rC0_1 += m0;
               m0 = rA1 * rB1;
               rC1_1 += m0;
               pA0 += incAk0;
               pA1 += incAk0;
               pB0 += incBk0;
               pB1 += incBk0;
               rB0 = alpha;
               rC0_0 *= rB0;
               rC0_1 *= rB0;
               rC1_0 *= rB0;
               rC1_1 *= rB0;
               *pC0 = rC0_0;
               pC0[1] = rC1_0;
               *pC1 = rC0_1;
               pC1[1] = rC1_1;
               pC0 += incCm;
               pC1 += incCm;
               pA0 += incAm;
               pA1 += incAm;
               pB0 += incBm;
               pB1 += incBm;
            }
            while(pA0 != stM);
            pC0 += incCn;
            pC1 += incCn;
            pA0 += incAn;
            pA1 += incAn;
            pB0 += incBn;
            pB1 += incBn;
         }
         while(pB0 != stN);
      }
   }
   if (k=N-Nb)
      ATL_dJIK0x0x48TN2x1x24_aX_bX(M, k, 48, alpha, ca, lda, cb + (Nb*ldb), ldb, beta, cc + (Nb*ldc), ldc);
   if (Nb && (k=M-Mb))
      ATL_dJIK0x0x48TN1x2x24_aX_bX(k, Nb, 48, alpha, ca + (Mb*lda), lda, cb, ldb, beta, cc + (Mb), ldc);
}
#ifdef incAm
   #undef incAm
#endif
#ifdef incAn
   #undef incAn
#endif
#ifdef incAk
   #undef incAk
#endif
#ifdef incBm
   #undef incBm
#endif
#ifdef incBn
   #undef incBn
#endif
#ifdef incBk
   #undef incBk
#endif
#ifdef incCm
   #undef incCm
#endif
#ifdef incCn
   #undef incCn
#endif
#ifdef incCk
   #undef incCk
#endif
#ifdef Mb
   #undef Mb
#endif
#ifdef Nb
   #undef Nb
#endif
#ifdef Kb
   #undef Kb
#endif
